project:
  type: book
lang: pt-br
title-block-author-plural: "Organizadores"  
toc-title: "Sumário"
indent: true

book:
  page-navigation: false
  title: "Pesquisa e atuação em Psicologia e políticas públicas"
  page-footer:
    right: | 
      Este livro foi construído com <a href="https://quarto.org/">Quarto</a>.
    left:
      <img src="./imagens/uva-brasao.jpg" width="100"> 
  cover-image: cover_pt.png
  #cover-image-alt: |
    #A imagem mostra a capa do livro Produções Técnicas em Psicologia: Experiências Compartilhadas. No topo da capa, em fonte menor e de cor preta, estão as siglas PPGPSI e PPGPPPP, seguidas pelo nome Universidade Federal do Ceará, indicando a associação com a instituição. O título principal é apresentado em letras grandes e negrito, com Produções Técnicas em verde e em Psicologia em preto, abaixo do qual está o subtítulo Experiências Compartilhadas em fonte menor e itálico. Centralizado na capa há o desenho de uma ave, um carcará, em voo, com as asas abertas e o corpo voltado para a esquerda, delineado em traços pretos. O pássaro carrega uma cobra em suas garras. Abaixo do desenho, em letras pretas menores, estão os nomes Francisco Pablo Huascar Aragão Pinheiro e João Paulo Pereira Barros, seguidos pela palavra Orgs., sugerindo que são os organizadores da publicação. A capa tem um fundo claro e o design geral é simples.
  repo-url: https://github.com/pablo-huascar/livro-ppgpppp-2024
  repo-branch: main
  favicon: cover_pt.png
  reader-mode: true
  

  chapters:
    - index.qmd
    - introduction.qmd
    - institucional.qmd
    - conselho_editorial.qmd
    - folha_de_rosto.qmd
    - part: Capítulos em português
      chapters:
        - neta_reescrevendo.qmd
        - rodrigues_trabalho.qmd
        - aragao_saude_trans.qmd
        - barbosa_aquilomba.qmd
        - nascimento_muros.qmd
        - pessoa_narrativa.qmd
        - santiago_escolarizacao_trans.qmd
        #(15) - sousa_violencia.qmd
        #(17) - sousa_silva_saude_homens_trans.qmd
        #(19) - barbosa_hiara.qmd
        #(21) - janne_camila.qmd 
        - sobre_os_autores.qmd
    - part: Chapters in English
      chapters:
        - neta_reescrevendo_en.qmd
        - rodrigues_trabalho_en.qmd
        - aragao_saude_trans_en.qmd
        - barbosa_aquilomba_en.qmd
        - nascimento_muros_en.qmd
        - pessoa_narrativa_en.qmd
        #(14) - santiago_escolarizacao_trans_en.qmd
        #(16) - sousa_violencia_en.qmd
        - souza_silva_saude_homens_trans_en.qmd
        #(20) - barbosa_hiara_en.qmd
        #(22) - janne_camila_en.qmd
        - about_the_authors.qmd


format:
  html:
    smooth-scroll: true
    anchor-sections: true
    theme: 
      - cosmo
      - livro-ppgpppp-2024.scss
    callout-appearance: simple
    toc: true
    toc_float: true
    toc-depth: 2
    standalone: true
    indent: true
    code-link: true
    code-tools: true  
    code-line-numbers: false
    code-copy: true
  

    author-meta: "Francisco Pablo Huascar Aragão Pinheiro e Emanuel Meireles Vieira"

editor: visual
csl: apa.csl


