project:
  type: book
lang: pt-br
title-block-author-plural: "Organizadores"  
toc-title: "Sumário"
indent: true

book:
  page-navigation: false
  title: "Pesquisa e atuação em Psicologia e políticas públicas"
  page-footer:
    right: | 
      Este livro foi construído com <a href="https://quarto.org/">Quarto</a>.
    left:
      <img src="./imagens/uva-brasao.jpg" width="100"> 
  cover-image: cover_pt.png
  cover-image-alt: |
    A imagem é a capa de um livro intitulado Pesquisa e atuação em Psicologia e políticas públicas. No topo esquerdo, há o logotipo das Edições UVA, que apresenta um desenho estilizado de uma caneta dentro de uma linha horizontal, com o texto Edições UVA ao lado. No centro da capa, há uma ilustração em preto e branco que mostra um cacto com dois bulbos e um botão de flor, voltado em direção a um sol brilhante com raios desenhados de forma simples. Na parte inferior da capa, estão os nomes dos organizadores: Francisco Pablo Huascar Aragão Pinheiro e Emanuel Meireles Vieira, seguidos do termo Orgs.
  repo-url: https://github.com/pablo-huascar/livro-ppgpppp-2024
  repo-branch: main
  favicon: cover_pt.png
  reader-mode: true
  

  chapters:
    - index.qmd
    - introduction.qmd
    - institucional.qmd
    - conselho_editorial.qmd
    - folha_de_rosto.qmd
    - part: Capítulos em português
      chapters:
        - neta_reescrevendo.qmd
        - rodrigues_trabalho.qmd
        - aragao_saude_trans.qmd
        - barbosa_aquilomba.qmd
        - nascimento_muros.qmd
        - pessoa_narrativa.qmd
        - santiago_escolarizacao_trans.qmd
        - sousa_violencia.qmd
        - sousa_silva_saude_homens_trans.qmd
        - barbosa_hiara.qmd
        - janne_camila.qmd 
        - sobre_os_autores.qmd
        - indice_remissivo.qmd
    - part: Chapters in English
      chapters:
        - neta_reescrevendo_en.qmd
        - rodrigues_trabalho_en.qmd
        - aragao_saude_trans_en.qmd
        - barbosa_aquilomba_en.qmd
        - nascimento_muros_en.qmd
        - pessoa_narrativa_en.qmd
        - santiago_escolarizacao_trans_en.qmd
        - sousa_violencia_en.qmd
        - sousa_silva_saude_homens_trans_en.qmd
        - barbosa_hiara_en.qmd
        - janne_camila_en.qmd
        - about_the_authors.qmd


format:
  html:
    smooth-scroll: true
    anchor-sections: true
    theme: 
      - cosmo
      - livro-ppgpppp-2024.scss
    callout-appearance: simple
    toc: true
    toc_float: true
    toc-depth: 2
    standalone: true
    indent: true
    
  

    author-meta: "Francisco Pablo Huascar Aragão Pinheiro e Emanuel Meireles Vieira"

editor: visual
csl: apa.csl


