---
author: 
  - name: Vera Silvia Paula Pessoa Aguiar Neta
    url: http://lattes.cnpq.br/5191203280726899
    orcid: 0009-0009-1704-1451
    email: verasppan@alu.ufc.br 
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Gracymara Mesquita Severiano
    url: http://lattes.cnpq.br/6973773546458473
    orcid: 0000-0001-6813-8258
    email: gracymesquita@hotmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: João Pedro do Nascimento Malheiros
    url:  http://lattes.cnpq.br/8826984722634469
    orcid: 0009-0007-7710-3277
    email: pedromalheiros@alu.ufc.br 
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Amanda Cristina Carvalho Fontenele
    orcid: 0009-0003-6433-7585
    email: amandacarvalhofontenele@alu.ufc.br 
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Tereza Milena Andrade de Oliveira
    orcid: 0009-0003-2858-6234
    email: terezamilena@alu.ufc.br 
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Iratan Bezerra de Sabóia
    url:  http://lattes.cnpq.br/4256908254336676
    orcid: 0000-0003-3312-9954
    email: iratan@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: neta_reescrevendo.bib
reference-section-title: Referências
---

# Reescrevendo minha história: um aprendizado para a construção de possíveis projetos de vida

## Introdução

Reescrever a própria história é um processo de construção de um novo projeto de vida, resultado da ampliação dos horizontes de possibilidades que cercam os sujeitos e da devida integração mútua das possibilidades que disso emergem. Essa integração é aqui entendida como reafirmação do sujeito na realidade social, que se torna capaz de não somente participar dela, mas de transformá-la [@Freire1999]. Trata-se, pois, da oportunidade de contemplar a vista do futuro para além das imposições imediatas e frias de uma materialidade opressiva e desigual, não segundo uma lógica ingênua e idealizada, mas a partir da óptica de um sonhar revolucionário.

Em uma perspectiva freiriana, o sonhar, o ato de elaborar sonhos ainda que divergentes da expectativa de seus educadores [@Freire2014], é um dever e um direito político do educando. Destaca-se aqui o papel transformador da educação e do educador em iluminar no sujeito educando as múltiplas trajetórias e os projetos de vida possíveis a ele, com metodologias que acrescentem algo a seu repertório sociocultural, contribuindo para a tecitura de novos sentidos, novos valores, que favoreçam a construção de novos sonhos.

No entanto, conforme avalia Bourdieu [-@Bourdieu2007], o modelo escolar conservador opera em movimento contrário: encobre, como estratégia dominante de manutenção das desigualdades sociais em vigor, as possibilidades de sonhar. É um fenômeno nítido, sobretudo quando se avalia a possibilidade de acesso ao Ensino Superior, ainda turvo no imaginário das classes populares. O autor igualmente destaca a desigualdade de informações como fator potencializador, que se soma ao carente capital cultural sintomático da família marginalizada.

Desse modo, há dificuldades no recurso imaginativo do sujeito marginalizado para cristalizar o sonho do Ensino Superior, uma vez que ele aparece como um horizonte nublado, um trajeto pedregoso potencialmente inviável de ser seguido. A lógica neoliberal de ensino agrava a situação à medida que a escola é sequestrada pelo tecnicismo econômico e transformada em refém de reprodutibilidade de lucro, negligenciando a si mesma enquanto espaço de promoção de criticidade, autonomia e emancipação [@Laval2019].

Essa dubiedade do papel escolar é explorada por Severiano [-@Severiano2021], a partir da investigação do Projeto de Vida como disciplina e “conceito-alvo” do plano educacional, além da atuação dos estudantes no curso da disciplina. O processo formativo dos discentes da disciplina Projeto de Vida consultados pela autora neste trabalho é ofertado pelo Instituto de Corresponsabilidade de Educação [@ICE_EscolaDaEscolha, para. 04], que define a proposta do Projeto de Vida enquanto “solução central … para atribuir sentido e significado do projeto escolar na vida do estudante e levá-lo a projetar uma visão de si próprio no futuro, apoiado por todos que conjugam esforços, talentos e competências”.

No entanto, a pesquisa da autora aponta, avaliando o conteúdo relatado pelos professores que, apesar de haver um potencial transformador na disciplina enquanto espaço em que se tecem sonhos e se compartilha uma formação crítica de estímulo ao protagonismo dos estudantes, ainda há marcas amargas de neoliberalismo enraizadas não apenas no discurso dos docentes, mas também no próprio planejamento estrutural da disciplina: o Projeto de Vida passa a ser entendido como um exclusivo projeto de carreira profissional e desempenho no mercado, endossando a perspectiva do sujeito unidimensional, que se realiza apenas na dimensão de ser econômico de mercado [@Marcuse2015]. Nesse movimento, o que antes era um cidadão estudante em formação passa a ser uma espécie de funcionário a cumprir uma meta, o qual, nessa lógica, responde individualmente pelo seu fracasso institucional e financeiro.

Em contrapartida, “... não podemos inferir que a disciplina de Projeto de Vida esteja sendo usada unicamente para a construção de um ensino que visa atender as demandas econômicas e mercadológicas” [@Severiano2021, p. 17]. Desse modo, destaca-se que é possível extrair uma potencialidade transformadora na disciplina, articulada de modo a construir, inclusive, um afronte ao modelo neoliberal de ensino. Freire [-@Freire2014] distingue a educação conservadora da prática educativa progressista. Ele descreve que a educação conservadora opta por revelar apenas a verdade dos dominantes, ocultando a possibilidade do educando de adentrar nas verdades que o impulsionam à transformação de si e de seu meio. A segunda, no entanto, desnuda a verdade potente de que o sujeito é sujeito histórico-social-cultural, de que todo espaço social é também o seu espaço.

Não podemos nos eximir da posição de que, no atual contexto, a educação tem servido mais à formação de trabalhadores docilizados que de cidadãos ativos. O contexto educacional não apenas emula, de muitas formas, a ideologia mercadológica, mas converge para ser um aporte do mercado de trabalho acrítico que o neoliberalismo deseja. Pensar na educação de forma ampla é também pensar na reformulação do mundo do trabalho, das relações sociais, da qualidade de vida e do direito ao usufruto do tempo livre, pois, como destaca Demo [-@Demo1996], a pobreza se apresenta na privação de direitos fundamentais.

Se consideramos que a educação hoje cumpre esse papel de formar trabalhadores, dada a centralidade do trabalho na vida contemporânea [@Castel2003; @DalRosso2008; @DalRosso2017; @Saboia2019], existe uma forte tendência a replicar, na educação, as estruturas do mercado de trabalho. Entre elas, a reprodução de certa predefinição na ocupação de alguns espaços por determinadas camadas da sociedade se mostra particularmente notável no que diz respeito ao ensino profissionalizante e ao Ensino Superior.

Frente à problemática exposta, o projeto de extensão “Reescrevendo Minha História”, vinculado ao Laboratório de Estudo das Desigualdades e Diversidades (LAEDDES), objetiva estabelecer um vínculo entre estudantes do Ensino Médio da rede pública e do Ensino Superior, na figura da Universidade Federal do Ceará – *Campus* Sobral, possibilitando que o ingresso universitário seja somado ao repertório de horizontes desses estudantes. O projeto compreende o campo universitário como espaço de transformação da realidade, o qual, portanto, precisa ser representativo em seu meio, contemplando as mais diversas camadas do tecido social.

Assim, por meio das ações formativas nas escolas, discentes e docentes universitários vinculados ao projeto conseguem acessar o seio educacional do Ensino Médio e estabelecer, em sala, um terreno fértil ao compartilhar saberes entre estudantes. Instrumentalizados com recursos artísticos, perguntas disparadoras e exercícios de escuta, os extensionistas do projeto logram debater, com leveza e criticidade, temáticas-chave como cidadania, oportunidade, ingresso ao Ensino Superior, sistema de cotas, entre outras. O objetivo em questão não é colonizar horizontes com o ingresso universitário, mas trabalhar no campo da expansão, da possibilidade de tecer novos sonhos, entrever novas possibilidades e enxergar que o Ensino Superior é, também, um lugar que esses jovens podem ocupar. A proposta do projeto é também sinérgica ao potencial transformador da disciplina de Projeto de Vida, de modo que se possa estabelecer uma rede de diálogos frutíferos e mutuamente fortalecedores para assim catalisar o conhecimento enquanto cidadania ativa.

## Método

Com o propósito de democratizar o acesso ao Ensino Superior e promover a transformação social, o projeto “Reescrevendo Minha História” visa contribuir para a superação das desigualdades sociais. A iniciativa, que conta com a participação de alunos e professores, utiliza conhecimentos da Sociologia, Filosofia e Psicologia Social para abordar temas como desigualdade social e oportunidades educacionais.

Objetivando ampliar as oportunidades educacionais para jovens de escolas públicas, o projeto “Reescrevendo Minha História” foca na democratização do acesso ao Ensino Superior, apresentando a universidade como um espaço de transformação social e de exercício da cidadania, um projeto, portanto, a ser considerado. Através de quatro encontros, os extensionistas abordam temas como o sistema de cotas, as políticas de permanência estudantil e a importância da educação para o exercício da cidadania, estimulando o processo de reflexão crítica e construindo novos significados que podem ser vinculados aos projetos de vida.

Há uma formação interna com os participantes do “Reescrevendo Minha História” que consiste na familiarização com as atividades e os instrumentos a serem utilizados, na qual os extensionistas veteranos atuam como mentores, reproduzindo os encontros com os novatos em um formato de treinamento prático. Após cada sessão de preparação, é promovido um espaço para discussão e troca de saberes, visando o aprimoramento contínuo da ação, e ocorrem também acompanhamentos quinzenais com o coordenador. Além disso, os extensionistas novatos participam das ações primeiramente como ouvintes, para que possam se familiarizar e estar mais seguros para as próximas ações.

O primeiro encontro inicia-se por um momento de socialização entre extensionistas e alunos da escola, com o objetivo de estabelecer um vínculo de confiança. Em seguida, os objetivos do projeto são apresentados, enfatizando a importância do sigilo das informações compartilhadas. A primeira dinâmica consiste na aplicação do Instrumento Gerador de Mapas Afetivos (IGMA), desenvolvido por Bomfim [-@Bomfim2003], que permite investigar a relação afetiva dos estudantes com o espaço escolar.

Divididos em grupos menores para favorecer a expressão de sentimentos e emoções, os participantes, juntamente com os extensionistas, elaboram desenhos e listas de palavras que representam suas experiências escolares. Essa ação abre um espaço para que cada pessoa compartilhe sua história de forma única. É fundamental oferecer um olhar de esperança, acolhimento e compreensão, mostrando, assim, que é possível superar desafios e construir um futuro mais positivo, a fim de abrir a possibilidade de mudança. Para finalizar o encontro, uma pergunta disparadora é proposta: "O que vem depois da escola?". Essa pergunta serve para reflexão e discussão no encontro seguinte.

No segundo momento, ao se retornar à pergunta disparadora: a universidade aparece como possibilidade no plano de poucos alunos, pois que muitos não respondem ou mesmo demonstram falta de esperança para ingressar nesse projeto. Então, é iniciada a segunda atividade proposta, que consiste em uma adaptação da dinâmica da batata quente, na qual uma caixa contendo perguntas sobre o ingresso e a permanência na universidade, com foco na UFC, é circularmente passada entre os participantes.

Ao parar a música, o estudante com a caixa retira dela uma pergunta, à qual responde, abrindo espaço para que os demais participem e/ou ofereçam novas perspectivas. Caso eles não saibam a resposta, os extensionistas fornecem-na e perguntam se restou alguma dúvida. Dados coletados em diário de campo apontam que a maioria dos alunos demonstra desconhecimento sobre o funcionamento das universidades públicas, como formas de ingresso, cursos ofertados e políticas de permanência,.

No terceiro momento, é utilizada a canção de Bia Ferreira sobre a política de cotas como ponto de partida para a discussão. Após a apresentação musical, os estudantes são convidados a compartilhar suas percepções sobre o tema. Foi observado que, embora, inicialmente, muitos alunos tenham demonstrado desinteresse, falta de conhecimento sobre o tema ou noção superficial sobre as cotas, a música despertou um interesse genuíno pela universidade e pelas possibilidades de ingresso no Ensino Superior.

A partir daí, ao longo da discussão, é perceptível crescente curiosidade e engajamento. Essa mudança de postura sugere que a utilização de recursos como a música, que se conectam com a realidade e os interesses dos jovens, é fundamental para aproximá-los da temática e estimular a reflexão. É importante ressaltar que a escolha de temas e abordagens que dialoguem com o universo cultural e social dos estudantes é crucial para que eles se sintam parte do processo e se identifiquem com os conteúdos apresentados. Ao estabelecer um ritmo e uma linguagem que os jovens compreendam e valorizem, é possível criar um ambiente propício para o diálogo e a reflexão, imprescindíveis na construção de novos conhecimentos.

Para finalizar, no último encontro, os participantes são convidados a elaborar um cartaz coletivo com o tema “educação e oportunidade”. Durante a dinâmica, é observado que, embora os estudantes reconheçam a importância da educação para a melhoria de suas vidas, a perspectiva de cursar o Ensino Superior é vista como distante e pouco acessível.

No decorrer das ações, é solicitado aos extensionistas a elaboração de diários de campo após cada encontro na escola. Na área da extensão universitária, os diários de campo desempenham um papel crucial ao documentar as ações realizadas, as relações estabelecidas entre os estudantes e as ações, bem como os resultados alcançados por eles. O material coletado de forma individual pelos extensionistas é socializado nas discussões em grupo, contribuindo para uma construção colaborativa do saber e permitindo um olhar plural sobre as ações e os educandos, além de proporcionar uma relação entre a prática e as teorias estudadas durante a formação do extensionista.

## Resultados e discussão

As ações do Reescrevendo Minha História, desde sua organização interna com os membros até a ida a campo, estruturam-se na materialidade com a qual o laboratório trabalha, isso inclui o capital cultural dos estudantes, bem como o contexto histórico e social de suas vivências. De acordo com Severiano [-@Severiano2021], na escola há uma cobrança uniforme por sucesso, mesmo que haja um contexto de desigualdade na trajetória dos estudantes. Na lógica neoliberal, que foca essencialmente no resultado, a desigualdade não é levada em consideração na análise de sucesso alcançado. Em vista disso, a participação do LAEDDES nas escolas, utilizando-se das metodologias apresentadas, traz uma abordagem em que o estudante pode sonhar e desenvolver seu projeto de vida sem limitar-se a uma única possibilidade de experiência.

Enquanto facilitador de conhecimento, o projeto procura garantir uma maior inclusão nos dispositivos de saúde e educação para jovens. Entende-se que a universidade pública é um espaço que deve ser possível a todos, incluindo estudantes vindos de periferias, favelas, que estão em situação de vulnerabilidade social. O cenário desafiador no qual esses jovens estão inseridos não pode ser fator de exclusão para a recepção de informações que possam fornecer a eles bases para a construção de seu projeto de vida.

Nota-se que, durante os quatro encontros realizados na escola, é construído um vínculo entre os participantes e os extensionistas, o que se dá pela organização do projeto, pois que os extensionistas ficam responsáveis por todos os encontros em uma mesma sala, viabilizando um espaço de escuta que se dá pela própria organização do espaço, a partir da divisão da sala em grupos menores sob supervisão de um extensionista e do pedido para que o professor se retire da sala, a fim de deixar o ambiente o mais confortável possível para haver uma troca de experiências em relação às atividades propostas.

No primeiro encontro (aplicação do Instrumento Gerador de Mapas Afetivos), é comum que muitos estudantes demonstrem, por meio de falas, desenhos e escritos, a insatisfação com alguns professores e com a organização da escola no que concerne à estrutura física e à distribuição de aulas, comentando, muitas vezes, que raramente suas reclamações são ouvidas pelos professores ou pela coordenação. Além de falarem sobre sensações decorrentes de cansaço e exaustão devido à realização de outras atividades ao longo do dia, como trabalho.

Entretanto, mencionam o espaço escolar como essencial para o aprendizado, além de ser importante para criar e manter amizades. Eles também expressaram emoções positivas, como alegria, companheirismo e sonhos para o futuro. Nesse quesito, embora verbalizem aspirações que transcendem o ambiente escolar, seus projetos de vida tendem a ser limitados por uma percepção de que a universidade é um espaço inacessível.

Os extensionistas são treinados em uma capacitação interna do projeto para validar as experiências ali compartilhadas, dando a devida atenção a todos os participantes e a suas histórias e, ao mesmo tempo, promovendo uma concepção que não seja fatalista, que possibilite esperança em um futuro positivo, em que há espaço para mudanças e superação de adversidades. Isso se torna essencial quando nos deparamos com a ideia de a universidade ser um espaço impossível de atingir, representada principalmente por meio dos relatos dos estudantes, que muitas vezes não possuem incentivo familiar, escolar, ou tem de assumir outros projetos, como o trabalho, em detrimento do Ensino Superior.

A escola, muitas vezes, incentiva a competitividade e a disputa entre os alunos, que passam a ser avaliados pelo seu desempenho. Assim, em uma era neoliberal, a escola assume o formato de uma empresa [@Laval2019], classificando os alunos de acordo com notas que supostamente diferenciam os níveis de inteligência e desenvolvimento na aprendizagem. Muitos estudantes se sentem subjugados e desesperançosos frente a esse funcionamento escolar e não se consideram capazes de conseguir ingressar em um curso de nível superior, excluindo essa possibilidade de seus projetos de vida, focando em outras formas de obtenção de sucesso, como um emprego.

Os relatos dos estudantes indicam uma forte influência do contexto social e familiar, que muitas vezes não valoriza a educação superior como uma possibilidade real. A ausência de exemplos concretos de pessoas que romperam essa barreira educacional e a falta de incentivo no seu meio social contribuem para a construção de um imaginário limitado sobre o futuro. Através da análise dos desenhos e das palavras escritas, busca-se compreender a experiência dos alunos no ambiente escolar e identificar os elementos que influenciam o estabelecimento do vínculo aluno-escola.

No segundo encontro (dinâmica da batata quente), os estudantes demonstram curiosidade e atenção em algumas perguntas, principalmente nas que fazem referência às bolsas, aos auxílios financeiros, ao funcionamento do Restaurante Universitário (a surpresa e a curiosidade diante dessas informações revelaram a necessidade de levar essas questões para os jovens). Durante a dinâmica, são discutidas questões sobre o ingresso e a permanência dentro da UFC, o que chama bastante a atenção dos estudantes.

É comum que muitos deles passem a conhecer sobre essas questões a partir da dinâmica e comecem a ver a universidade pública como uma possibilidade para eles, principalmente quando algum extensionista relata sua própria experiência de ingresso na UFC por meio das cotas ou da lista de espera e de permanência na universidade com as bolsas, os auxílios e o acesso a refeições de baixo custo (ou gratuitas). Isso aproxima os estudantes cada vez mais dessa realidade, que passa a ser também uma possibilidade, pois essa falta de informação limita a visão de futuro desses jovens, restringindo suas expectativas profissionais a cargos operacionais, como se essa fosse a única opção para suas vidas.

No terceiro encontro (música de Bia Ferreira sobre cotas), os estudantes são incentivados a compartilhar suas percepções acerca da música e do tema. É importante salientar que alguns deles afirmam que não possuíam conhecimento sobre a dinâmica das cotas até o jogo da batata quente. A utilização da música demonstra resultado positivo na medida em que causa uma aproximação dos jovens com a temática, o que é percebido devido ao engajamento deles em torno do tema à medida que a discussão vai tomando cada vez mais forma dentro da sala de aula.

Com um ritmo e uma linguagem acessível, mas com um tema complexo que demonstra a vivência da artista, a música possibilita uma aproximação do discurso para a realidade dos jovens, que muitas vezes compartilham suas opiniões e perguntas sobre o funcionamento das cotas dentro da universidade. Há, portanto, a construção de um ambiente propício para debates, discussões e pensamento crítico.

Por fim, no último encontro, é realizada a produção de cartazes, e, durante o processo, os participantes evidenciam o valor e a importância da educação, sendo considerada muitas vezes uma oportunidade para melhorar de vida. Apesar disso, a universidade pública muitas vezes não é uma realidade considerada possível ou acessível a eles. Durante a realização da atividade, são levantadas pautas muito importantes pelos próprios participantes, como a questão de oportunidades e questionamentos sobre o futuro após a saída da escola.

Nota-se que os estudantes começam a desenvolver um senso crítico quanto aos seus direitos no que concerne à educação, assim como um interesse em ocupar espaços públicos, como a universidade.

## Considerações finais

Tendo em vista todo o aparato constituinte que a educação pode ter na vida do sujeito como uma ferramenta transformadora em suas trajetórias, ações de cunho informativo e integrador como as do LAEDDES apresentam variedade de caminhos disponíveis para a construção de projetos de vida. Freire [-@Freire2014], ao trazer o que difere uma educação conservadora de uma educação prática, apresenta que esta segunda consiste em trazer para o educando uma visão transformadora do sujeito histórico, social e cultural, bem como uma visão de si como um ser capaz de mudanças do meio em que vive.

Os resultados das ações são alcançados à medida que, apesar da percepção inicial dos estudantes, a atividade desencadeia um processo de reflexão sobre o futuro. Um número significativo de jovens demonstra maior interesse pelas informações sobre a universidade, evidenciando uma mudança de postura em relação ao Ensino Superior.

A análise das discussões em grupo revela que os participantes apresentavam um conhecimento limitado sobre seus direitos e uma forte associação entre a cidadania plena e a classe social. As narrativas evidenciam as desigualdades sociais e as dificuldades enfrentadas em seus contextos de vida, o que limita suas expectativas em relação ao futuro. Diante desse cenário, a presença de egressos da escola pública no grupo de extensionistas mostra-se fundamental para a construção de pontes entre os estudantes e a universidade, pois a identificação proporciona uma nova perspectiva sobre as possibilidades de vida por meio da educação.

É possível destacar um alinhamento entre as ações desenvolvidas pelo LAEDDES e a disciplina de Projeto de Vida. Enquanto esta tem o objetivo de auxiliar o aluno a desenvolver seus projetos, considerando sua realidade social e seu protagonismo nas escolhas a serem feitas, o Laboratório cumpre o papel de democratizar as informações sobre o ingresso no espaço do Ensino Superior na rede pública.

Ao possibilitar uma maior abrangência nas visões que esses sujeitos têm de seu futuro, o projeto “Reescrevendo Minha História” proporciona uma mudança positiva no que tange a um conhecimento maior sobre a universidade, as oportunidades para adentrar, ocupar e pertencer a esses espaços, assim como um maior desenvolvimento do senso crítico que esses jovens têm sobre suas vidas e seus planos futuros.

Por meio da análise dos resultados das ações, bem como dos relatos narrados por extensionistas que participaram do projeto durante suas trajetórias escolares na rede pública e ingressaram na universidade pública posteriormente, afirmamos o cumprimento do principal objetivo do projeto: proporcionar o conhecimento sobre a universidade e possibilitar a democratização do ingresso nela como um dos caminhos a serem seguidos após a saída do Ensino Médio. Por fim, ao propiciar uma diminuição da distância entre o ambiente universitário e as redes de ensino público, o projeto auxilia o cumprimento do direito de acesso à educação, sensibilizando e promovendo mudanças na vida desses sujeitos.
