---
author: 
  - name: Jocélia Maria Santos de Lira Pessoa 
    url:  https://lattes.cnpq.br/9851159050629101
    orcid: 0009-0006-3186-8381
    email:  jocelialira@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Rita Helena de Sousa Ferreira Gomes
    url:  http://lattes.cnpq.br/9324470543610163
    orcid: 0000-0002-2306-4264
    email: ritahelenagomes@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
lang: en
toc-title: "Table of contents"
language: 
  title-block-author-plural: "Authors"
filters:
  - section-bibliographies
bibliography: pessoa_narrativa.bib
reference-section-title: References
---

# Autobiographical narratives with middle school students: Perceptions of public policies

## Introduction

This article results from research conducted within the Professional Master's Program in Psychology and Public Policies. The study employed autobiographical narratives from middle school students in Sobral, Ceará, who identified and gave meaning to the public policies that influence the schooling process, recognizing their weaknesses and strengths.

According to the National Education Guidelines and Framework Law (LDB), the school forms citizens by promoting their development and expanding social interaction. The relationships developed within the educational context confer community significance.

For Moreira (2020), school is a space for developing autonomy and a critical capacity for constructing different identities and confronting violence and exclusion. Thus, we propose reconsidering the school as an organization that, beyond cognitive aspects, aims for wholeness and is concerned with social issues and the public policies directly linked to them. Therefore, it is necessary to revisit and discuss which philosophies, guidelines, and paths are being utilized by education, their effectiveness, and their acceptance by the school community.

Gonçalves (2010) states that "social public policies represent, in contemporary Brazilian society, a space for the promotion of rights, aimed at overcoming social inequalities" (p. 19). But does this promotion of rights happen? Is there a reduction in social inequalities, or do we continue to wait for redemptive public policies? Carvalho (2015) reiterates that public education policies "can contribute to addressing the major contradictions and problems of our society, such as, for example, the deprivation of rights of children who require social protection policies" (p. 28).

However, it is necessary to assess whether these policies are aligned with the interests of the population and region, as the applicability of a public policy is not universal. When we idealize the subject, we reinforce the maintenance of social inequalities. Individuals are affected differently by public policies that they encounter. The subject is historical and has a unique subjectivity. Thus, public policies yield different results in their implementation, as a standard model is applied to various regions, cultures, and interests.

In light of these questions, we infer that a schooling trajectory marked by successive negative and unstimulating experiences both inside and outside the school makes the learning process fragile, compromising the integral development of the individual. “The adolescent is an active subject, constructing their development while also receiving influences from society and the environment in which they are inserted” (Seabra & Oliveira, 2017, p.641).

The school needs to be a space for growth, providing intentional schooling through public policies and making their importance and the reasons behind their implementation understood. Difficulty accessing public policies can lead to exclusion, whether due to dropping out or differences from a standard already experienced by families within society. Furthermore, access alone does not guarantee overcoming difficulties or developing critical awareness to question these models, as “we are aware that, in structurally unequal societies, public policies aimed at guaranteeing social rights are an ideological strategy for legitimizing the capitalist order, which depoliticizes the majority of the population” (Patto, 2022, p.16).

Given this scenario, autobiographical narratives, the methodology used in this research, served as a strategy to encourage children and young people to recognize social inclusion spaces, critically position themselves against internalized standards, and understand themselves as political subjects. By proposing to think and rethink public policies, the research sought to promote in participants a perception of themselves as subjects of rights, whether guaranteed or denied.

Bringing up school memories through autobiographical narratives is a fruitful strategy for understanding the meaning attributed to the school environment, indicating how much our experiences shape us as individuals. Moreover, the narratives presented can encourage the development of new educational practices that consider the holistic development of individuals in relational, cultural, cognitive, emotional, social, and historical aspects (Neto & Santos, 2017, p. 562).

Public policies in the field of education permeate the school and its actors. Within a process of building comprehensive education, there is an ideal space for discussion about these policies and their short-, medium-, and long-term effectiveness. Carvalho (2015) continues the discussion that the school should consider all dimensions of life in the development of children, not forgetting that they should be seen as subjects, even if equal access to rights does not exist among them.

## Method

The method used in this research was autobiographical narratives. According to Furlanetto (2020), this source of investigation is supported by the narration of lived experiences. These narrations are made by the subjects who lived them. Freitas and Galvão (2007) state that "autobiographical narratives bring in their personal elaboration the idiosyncratic meaning of life experiences and bring forth the identity processes of the subjects' insertion into social groups" (p. 227). This interactive and dialogical methodology promotes a reflective and re-signifying process when participants can narrate their own experiences. Furlanetto (2020) emphasizes that:

Biographical (auto) research, as it has been developing in Brazil, questions not only the relationships of adults with the world of life but also how children, adolescents, and young people maintain and build values and beliefs in their relationships with what is proposed to them by the institutions that welcome them (p.49).

Collective narratives promote reflective spaces for constructing meaning out of narrated events. “It is, therefore, through narration and in the narration produced that children, young people, and adults conceive and perceive themselves in (trans)formation through retrospective, interactive, and prospective movements enabled by the act of narrating their own experience” (Passegi *et al*., 2016, p.53). This method affirms the recognition of the empowerment of the subject, whether child, elderly, or adult, who narrates and analyzes their own stories, becoming the rightful subject of this process. These narratives are freely expressed through drawings, texts, oral stories, dances, among others. Costa and Astigarraga (2021) affirm that "in reflexivity, the narrator projects onto themselves, formulates their thoughts, and through their knowledge, builds and structures their experiential baggage, assuming the position of the protagonist of life" (p. 3). Data collection occurred through conversation circles, as they allow and offer enhanced listening through horizontality and dialogicity (Furlanetto *et al*., 2020).

The institution chosen for the research was a full-time school located in a peripheral neighborhood in the city of Sobral, Ceará. The two inclusion criteria for the study were completing all elementary education in public schools and regularly enrolling in the 9th grade. The choice of students from this grade was due to their completion of the elementary education cycle. Attending basic education in public schools ensures that these students had their school journey marked by public policies, an important fact for the research objectives. All names are fictitious in preserving the identity of the research participants.

## Results and Discussion

The excerpts analyzed are transcripts of the meetings and discussions among the participants. The themes that emerged most frequently and intensely were brought forward for analysis. The content of the participants' narratives is unique as it comes from personal experiences. However, when analyzed collectively, they are similar in many excerpts and build the group's identity. Similarities stem from adolescence, their territory, their plans and insecurities about the future, and their school journey, which became the same when they moved to the same neighborhood. Kramer (2016) states that "when negotiating the construction of memory in relation to one's own memories and the memories of others, the subject changes, as there is an intimate relationship between memory and identity" (p. 35).

### School

In the narratives, the school emerged as a place of acceptance, affection, and learning, a place of safety and protection, and a refuge from family and personal problems. Nóvoa and Alvim (2021) present the school as a space for many, a collective journey, different from the home, which is an individual space. This difference between the two spaces is important and necessary. Therefore, family and school must work together, as their different realities complement students' education.

Besides having my problems at home, I don't like to bring them to school. I think school is a very fun place for me. That's why I love being in the classroom, I love being with the boys, I do my activities. Then I talk, and even though I shout a little in the classroom, I like school. I prefer school a thousand times over my house. ... People say: oh, she's always shouting. But I always do this to forget everything that happens at home (Sara).

The affection in schooling and the relationships that permeate it compete with the demand for results as students progress in their education. There is no loss of "enchantment" but more significant fatigue and exhaustion with these demands. Excessive Portuguese and math classes, question banks, and weekly tests. The demands are rewarded with prizes for the classes that reach the stipulated goals. Students make an effort to win pool parties, outings, chocolates, and trips to the movies, generating a mix of feelings when these memories come up in the narratives.

I think those years with the more important exams are years that really mark a student's life. The teachers made us study a lot. Learn things that nowadays aren't so important, but at the time, 'Oh my God, I can't believe it,' but it was really good. It's because it marks us a lot—besides learning, we had fun, especially on the school Saturdays when we could play with water. We'd get the bucket and soak ourselves. (Lua).

But it's a bit exhausting because, by fifth grade, it's not something out of this world to worry about, not that much, and we're pushed harder because we have to master several skills. If I'm not mistaken, this year we have 59 or 49 skills to learn throughout the year, okay? But for me, in my opinion, it's a lot (Lua).

Another highlight in the narratives is the reference to teachers as mediators of learning, playing an important role by exercising their pedagogical presence. They become essential actors in the narratives, whether in joyful scenes or scenes that evoke emotion. Rodrigues *et al*. (2021) argue that the learning process of children is permeated by emotions. Nóvoa (2021, p. 7\) states that teachers are necessary for education in the mission that “in proximity to families, local authorities, public and private entities, can build the conditions for an educational capillarity based on commonality and conviviality.” Affection positively influences the development of learners. Teachers' names always come with a story that marked that student's life.

### Full-Time School

The full-time school is a proposal regulated by the federal government and aims to expand the offer of elementary schools in a full-time format. A full-time student is assured three daily meals, a greater supply of learning materials, and stays at school for nine hours daily, reassuring guardians who work outside the home.

However, there is a need to discuss the quality of the provision of this type of education and the implementation format of the diversified curriculum. The physical structure of the buildings, exhaustion, demands for results in large-scale assessments, and the diversity of the menu also need to be debated. When a student remains nine hours a day within a school institution, quality cognitive, emotional, social, and critical education is even more essential. “Thus, full-time education can play an important role in transforming the functions of public education. Such transformation is based on how its audience has been treated” (Carvalho, 2015, p.38). Libâneo (2016) strengthens the critical stance of evaluating how and why choices in education are made:

Recent studies indicate, for example, that one of the most present guidelines in World Bank documents is the institutionalization of poverty relief policies expressed in a conception of school as a place of shelter and social protection, where one of its ingredients is the implementation of an instrumental or results-based curriculum. Such policies bring with them the disfigurement of the school as a place of cultural and scientific formation and, consequently, the devaluation of meaningful school knowledge (p. 40).

The narratives bring experiences of enchantment, limitations, and exhaustion with this type of education.

The full-time school is a good thing and, at the same time, exhausting. Because it's good because we develop more than other schools, we have more diverse classes, we spend more time with our classmates... But at the same time, for me, it's exhausting. It demands a lot; we wake up early and come home after hours. Nine hours at school, with three breaks that are morning snack, afternoon recess, and afternoon break. Every time I get home, I'm very tired. I just want to sleep. (Lua).

### Bullying

... at first, I was bullied. The boy, the boy took my glasses and ran away with my glasses. I cried. Then I screamed for Aunt Rosa, who helped me because I was very blind... I'm going to cry... I'm very fragile about telling these things (Sara).

The term bullying originates from English, with bully meaning "aggressor," and bullying can be defined as "aggressive behavior." It has rapidly and violently advanced within the school environment and permeated the autobiographical narratives of all participants.

The country has expressed concern, and in an attempt to discuss and eliminate bullying, in 2015, Law No. 13.185 was enacted, establishing the Program to Combat Systematic Intimidation (Bullying). The law uses the term "systematic intimidation". It defines bullying as "any act of physical or psychological violence, intentional and repetitive, that occurs without apparent motivation, practiced by an individual or group, against one or more people, with the aim of intimidating or assaulting them, causing pain and anguish to the victim, in a power imbalance between the parties involved" (Brazil, 2015).

Nascimento and Menezes (2013) argue that bullying "is not an act of gratuitous aggression, but rather a situation of violence marked by discrimination and prejudice, socially constructed and sustained by a school culture that remains oblivious to this phenomenon" (p. 146). Although this is a discussion before the national law, the scenario has not shown positive changes and continues to generate suffering in students who are victims of this violence. Promoting a culture of peace, talking about differences, welcoming victims, and encouraging that bullying cases are not silenced may bring visibility and possible changes in the approach to this issue, which leaves marks on the lives of these students.

My mother had already noticed that I was very depressed in the seventh grade. I was very sad, saying I didn't want to attend school. Because, guys, I was bullied a lot, right? Let's be honest, I didn't like it, and I was almost becoming depressed. (Tibio).

### Pandemic

I don't know about you, but the pandemic really affected me. To this day, there are sequelae (Tíbio).

The narratives brought up the impacts of the COVID-19 pandemic that need to be analyzed: difficulty keeping up with remote classes, mental health. The year 2020 was a turning point in the new format of education.

In 2020, everything changed. With the pandemic, the long school century, which began 150 years earlier, ended. The school, as we knew it, ended. Now, a new school begins. The digital age has imposed itself on our lives, in the economy, culture, society, and also in education. Nothing was planned. Everything came suddenly. Brutally (Nóvoa & Alvim, 2021, p. 2).

Schools underwent technological adaptation to continue students' teaching and learning. However, we are not a country with guaranteed and equal digital accessibility for everyone, which results in differences in students' achievement and learning according to their social class.

Data from the Rede de Pesquisa Solidária from August 2020 show that, between March and July 2020, more than 8 million children aged 6 to 14 did not do any school activities at home. In July, while only 4% of the wealthiest children had no school activity, this number rose to 30% among the poorest children (Macedo, 2021, p.267).

The federal government failed to promote and guarantee thousands of students nationwide technological access. Macedo (2021) emphasizes that "by the end of 2020, despite some bills formulated in the Legislative branch, no federal public policy to guarantee connectivity and remote education for public school students had been approved in the country" (p. 268). These data demonstrate a gap between guaranteeing a public policy in the National Education Plan and supporting its effective implementation. The pandemic period left a learning deficit among students, especially those from poor classes.

Back then, I used my mother's cell phone, so I just did the activities and turned them in, but I didn't attend the classes (Vilma). 

I didn't attend the online classes (Lua).

In addition to difficulties in technological access, the discussion about the importance of mental health also gained visibility during the pandemic years. Jucá *et al*. (2021) state that "psychic pain, anguish, and fear are experiences that inscribe themselves with the advance of the pandemic, the mourning of daily life, the loss of relatives and acquaintances, the intensification of family coexistence (and conflicts), and the uncertainties about the resumption of classes" (p. 12). Mental health had never been talked about as much, and this prompted these adolescents to seek and discuss the importance of psychologists in their development.

### Territory (Invisible Walls)

The neighborhood where the participants live is a public housing policy and has become an important landmark in the life history of these adolescents. The walls surrounding it are invisible but noticeable in the fear, anger, helplessness, and discrimination its residents are subjected to. These 'walls' are delineated by orders from criminal organizations that promote insecurity among residents. The consequences of living in a peripheral and stigmatized territory are felt and described throughout the meetings.

Every time they ask me where I live or study, I say it's in Floresta because I don't dare say I live in Praia (Tibio). 

I'm afraid of dying. Praia is very discriminated against (Vilma). 

But man, I wanted to take each person who says that. Put them here for a day to see that it's not some otherworldly thing. We live a normal life just like they do, man. We have our house, our friends, and our school. We live a normal life (Lua). 

My mother isn't involved in anything, but she refuses to go to other neighborhoods because she already lost a sister because of these neighborhood fights. So, what marked me a lot was that my mother could never go to a school meeting. I was always the protagonist type, and every school dance, every play, I wanted to be there. I danced. But every time I saw the other mothers going, and mine never did. And there came a day when I got tired of waiting. I would go on stage already knowing she wasn't going to see me. This is a very striking part. And it wasn't because she didn't want to; it was because she couldn't. Presentation, June festival, Mother's Day dance, important meeting. When there was an Easter event, I was very sad because I wanted her there, and she wasn't going. So, I think that for my life, I even told my brother. She won't be able to go to his meetings either. But I told him that if one day there's something, I'll go, right? Because I don't want him to go through the same thing I did (Ana).

When we discuss territories and their representations, we generate other questions about the public policies connected to them. The intersection with security policies, which have both shown themselves to be failing in protecting residents of the neighborhood from the whims of factions, and at times have the public security agents themselves reinforcing stigma and violence toward peripheral subjects. Which ones have been prioritized to break the territory's stigma? What are these policies and projects producing and representing within the neighborhood? Do the inhabitants see themselves in these processes of collective construction?

Gonçalves (2019) argues that "it is important to rescue what has been said about this territory and, with that, problematize the visibility of some discourses and practices, to the detriment of the silencing of others, when it comes to favelas" (p. 131). There is an encouragement to discuss this territory in a non-stereotyped way, to open new paths. The narratives timidly bring the possibility of new actors. However, it is necessary to encourage these adolescents to discuss public policies with critical and constructive intent.

## Final Considerations

From the adolescents' narratives, it was possible to understand the importance of the school journey for good individual development, its meanings and senses within each one's life history, and the potential of the collective in discussing common milestones in school journeys. Public policies are powerful markers in these journeys.

Students seek spaces to speak, not just to learn. Speaking says a lot about oneself and one's desires. The use of autobiographical narratives with adolescents allowed visibility and voice. In their narratives, public policies directly linked to education emerged, such as full-time school, the Bolsa Família program, national food policy, and school supplies kit. However, other markers related to them also strongly emerged: bullying, the pandemic, and the territory in which they live. This combination of themes proves that the school is not an isolated institution but one permeated by the life stories of the individuals who make it up.

The school does not end in itself. Its validity needs to be expanded and intentional. The law and discourse are practical, coherent, and forward-looking. However, the day-to-day is exhausting.

The analyses of this research can contribute to professionals who think about and develop public policies directed at children and adolescents, providing support to evaluate the effectiveness of implementing and executing these policies. Furthermore, by promoting an environment of exchange and recognition of participants' narratives, the research could be perceived as a space of acceptance, well-being, and opportunity for self-recognition as a subject of rights.