---
author: 
  - name: Haline Maria Parente Rodrigues
    url: https://lattes.cnpq.br/6480643447721226
    orcid: 0009-0009-9680-820X
    email: verasppan@alu.ufc.br 
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Francisco Pablo Huascar Aragão Pinheiro
    url: http://lattes.cnpq.br/6949209482037074
    orcid: 0000-0002-5581-7996
    email: juliananascimento@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: rodrigues_trabalho.bib
reference-section-title: Referências
---

# Trabalho docente e saúde mental de professores brasileiros na pandemia da covid-19

## Introdução

Nos últimos anos, têm-se evidenciado um crescimento significativo de transtornos mentais entre professores [@Silva2018], situação que foi agravada com o trabalho remoto que passou a ser realizado durante a pandemia da Covid-19 [@Allen2020]. Nesse cenário, houve transformações abruptas no desenvolvimento da atividade docente sem o suporte necessário a essas modificações [@Oliveira2021]. A falta de acesso à internet e a computadores, bem como a baixa motivação de pais e alunos foram percebidas como barreiras ao desenvolvimento do ensino remoto [@Klapproth2020].

Além disso, a transição do ensino presencial para o remoto acentuou a precarização do trabalho docente [@Ferreira2021] e, em muitos casos, representou um aumento da carga horária e uma ampliação da flexibilização e da intensificação laboral [@Bernardo2020]. Observou-se, ainda, uma incompatibilidade do trabalho em home-office com as demandas pessoais dos docentes, uma vez que houve uma percepção de perda das vidas privada e familiar devido à realização, em casa, das atividades de trabalho [@Bernardo2020; @Santos2020], assim como uma invasão do tempo dedicado ao descanso [@Akour2020].

O trabalho online repercutiu nas interações durante as aulas e no processo de ensino-aprendizagem, na medida em que limitou as trocas entre professores e alunos [@Ferreira2021]. Além das adversidades específicas do trabalho docente, estressores que emergiram com a pandemia, como o isolamento social [@Silus2020], a fragilização das relações sociais [@Jakubowski2021] e o medo de perder o emprego [@Ferdous2020] também repercutiram na saúde mental dos professores.

Nesse contexto, as professoras tiveram maiores prejuízos em relação à saúde mental [@Allen2020;@HidalgoAndrade2021;@Klapproth2020;@Li2020;@Oducado2020; @OzamizEtxebarria2021]. É possível mencionar, ainda, a diminuição do engajamento dos estudantes, o aumento da carga horária [@Klapproth2020;@Silus2020], e a inaptidão com aparatos tecnológicos [@Araujo2020;@Kita2022] como fatores que propiciaram o adoecimento mental. Além disso, a falta de apoio institucional [@Kita2022] e a precarização do trabalho [@OzamizEtxebarria2021] também impactaram negativamente a saúde mental dos docentes.

Especificamente em relação ao contexto brasileiro, diversos estudos anteriores à pandemia da Covid-19 buscavam determinar a prevalência e os preditores de Transtornos Mentais Comuns (TMCs) entre docentes. Nesse contexto, uma pesquisa (n = 127) com professores de uma universidade pública brasileira observou uma prevalência de 29,9% de TMCs (Campos *et al*., 2020). Nível similar (29,7%) foi observado em um estudo com 679 professores do Ensino Fundamental (Carlotto & Câmara, 2015).

De forma distinta, outra investigação identificou uma prevalência de 49,5% de TMCs entre os 110 professores da rede municipal de ensino que foram entrevistados (Baldaçara *et al*., 2015). Por sua vez, uma pesquisa de natureza longitudinal conduzida com 265 professores de Ensino Fundamental mostrou uma incidência de 18% de TMCs (Rocha *et al*., 2021). Já no que consiste na avaliação da prevalência de TMCs em professores durante a pandemia da Covid-19, um estudo envolvendo 1.427 professores de diferentes níveis de ensino reportou que 69% do público feminino e 59,2% do masculino apresentaram indicativos de TMCs (Pinho *et al*., 2021).

No que tange à investigação de preditores, o sentimento de desgaste na relação com os alunos, a insatisfação em trabalhar na instituição de ensino (Campos *et al*., 2020), a falta de realização no ofício e a exaustão emocional apresentaram associações significativas com desenvolvimento de TMCs (Brun *et al*., 2021). Além disso, ambiguidade funcional, sobrecarga laboral, pouco apoio social no trabalho e baixa percepção de autoeficácia também se mostraram como preditores de TMCs (Campos *et al*., 2020; Carlotto & Câmara, 2015; Rocha & Souza, 2013). Essas características das relações socioprofissionais e da organização do trabalho se mostraram, assim, relacionadas ao maior risco para o desenvolvimento de TMCs (Brun *et al*., 2021).

Em síntese, os estudos indicaram que a pandemia da Covid-19 e o trabalho remoto trouxeram repercussões negativas para a saúde mental dos professores. Contudo, para compreender o impacto disso na saúde docente, ainda se faz necessário uma maior investigação das condições de trabalho em home office, a exemplo do ambiente e dos equipamentos utilizados nesse novo contexto. Além disso, permanecem inexploradas a organização laboral que se instituiu quando os professores passaram a ministrar as aulas *online*, assim como as novas formas de relações estabelecidas com a comunidade escolar durante as atividades remotas.

Dessa forma, o presente estudo teve como objetivo determinar preditores de TMCs em professores brasileiros que atuavam na rede pública de ensino durante a pandemia da Covid-19. Foram delineadas as seguintes hipóteses:

H1: as professoras terão maiores médias de TMCs;\
H2: a idade vai se associar negativamente aos TMC’s;\
H3: as médias mais altas de TMCs serão encontradas entre os professores negros, amarelos e indígenas (não brancos);\
H4: os docentes sem companheiro terão maiores médias de TMCs;\
H5: a renda vai estar associada negativamente com os TMCs;\
H6: os docentes cuja renda diminuiu após o início da pandemia da Covid-19 terão maiores médias de TMCs;\
H7: os professores do grupo de risco para Covid-19 apresentarão maiores médias de TMCs;\
H8: os docentes diagnosticados com Covid-19 terão médias mais altas de TMCs;\
H9: os professores que perderam amigos ou familiares para a Covid-19 apresentarão maiores médias de TMCs;\
H10: os professores de níveis de ensino mais elevado que atuam em mais de um nível de ensino terão médias mais altas de TMCs quando comparados com docentes da Educação Infantil;\
H11: as piores percepções da organização do trabalho estarão associadas a maiores níveis de TMCs;\
H12: as piores avaliações das condições de trabalho estarão ligadas a maiores pontuações de TMCs;\
H13: as relações socioprofissionais negativas se vincularão a pontuações mais altas de TMCs.

## Método

### Participantes

A amostra deste estudo foi composta por 14.374 professores brasileiros. A maioria dos respondentes era da região Nordeste (62,5%), seguida pelas regiões Sudeste (23,6%), Centro-Oeste (6,5%), Norte (5,6%) e Sul (1,8%). Quase 81% dos docentes eram do gênero feminino. A maior parte dos sujeitos se autodeclarou como pardo (52,8%), seguidos pela autoidentificação como branco (34,8%), preto (10,4%), amarelo (1,4%) e indígena (0,71%). A idade variou entre 18 e 74 anos (M = 42,1; DP = 9,4). Mais da metade dos docentes eram casados ou em união estável (59,4%).

A média da renda mensal domiciliar per capita dos participantes era de R\$ 2.073,9 (DP= R\$ 2.119,1). A maioria dos professores relatou que a renda familiar após a pandemia da Covid-19 se manteve estável (55,3%), embora 42,8 % tenham informado diminuição dos seus ganhos e 1,9% relatado aumento. Em relação ao nível de ensino em que lecionavam, 17,2% atuavam na Educação Infantil; 40,4%, no Ensino Fundamental; 12,0%, no Ensino Médio; 26,4%, em mais de um nível; e 4,0%, no Atendimento Educacional Especializado e na Educação de Jovens e Adultos. No que diz respeito à pandemia da Covid-19, 22,0% eram do grupo de risco para a doença. A maioria dos participantes (77,8%), contudo, respondeu que não a havia contraído, e 62,9% dos docentes informaram que perderam amigos ou familiares em decorrência do novo coronavírus.

### Instrumentos

O questionário utilizado no levantamento continha os seguintes instrumentos: Self-Reporting Questionnaire (SRQ-20) e Escala de Avaliação do Contexto de Trabalho Docente Remoto (EACTDR). Além desses, havia questões sociodemográficas (gênero, idade, renda familiar mensal, nível de ensino, tipo de contrato de trabalho, etc.) e perguntas relacionadas à pandemia da Covid-19 (p. ex.: “Você perdeu alguém próximo a você (amigo ou familiar) devido à Covid-19?”).

O SRQ-20 (SRQ-20; Harding *et al*., 1980 - adaptado por Gonçalves *et al*., 2008) é um instrumento composto por 20 questões e utilizado para o rastreio de Transtornos Mentais Comuns. Todas as suas assertivas (p. ex.: “Assusta-se com facilidade?” e “Sente-se inútil em sua vida?”) variam entre “sim” e “não”. Às respostas afirmativas é atribuído o valor 1, enquanto às respostas negativas é atribuído o valor 0. O resultado é analisado somando-se as questões de modo que uma pontuação igual ou superior a 7 indica a presença de TMCs (Gonçalves *et al*., 2008). No estudo de validação, o instrumento demonstrou consistência interna satisfatória (α = 0,86), bem como na presente investigação (α = 0,87).

A EACTDR (Cunha *et al*., 2024) foi desenvolvida a partir da Escala de Avaliação do Contexto de Trabalho (EACT) proposta por Ferreira e Mendes (2008). A versão final do questionário contou com 33 questões que avaliam três dimensões, a saber: condições de trabalho (α = 0,85; p. ex.: “O computador ou celular fica lento ou trava durante a realização do meu trabalho”), organização do trabalho (α = 0,93; p. ex.: “Preciso responder e-mails, ligações ou mensagens de trabalho que chegam fora do horário de expediente”) e relações socioprofissionais (α = 0,93; p. ex.: “Não há autonomia para decidir sobre as metodologias de ensino aplicadas nas aulas”). Os itens são respondidos com uma escala do tipo likert que varia de 1 (nunca) a 5 (sempre), e todos apresentam assertivas negativas, de modo que pontuações mais altas indicam piores avaliações do contexto laboral (Cunha *et al*., 2023).

No estudo de validação (Cunha *et al*., 2023), os índices de ajuste do instrumento foram satisfatórios (RMSEA = 0,073, 90% CI: 0,072 - 0,074, SRMR = 0,057, CFI = 0,985, TLI = 0,984). A medida também apresentou consistência interna adequada (condições de trabalho, α = 0,83, ⍵ = 0,87; organização do trabalho, α = 0,92, ⍵ = 0,94; relações socioprofissionais, α = 0,91, ⍵ = 0,94). No presente estudo, a pontuação de TMCs foi tomada como variável dependente, enquanto aquelas pertinentes ao contexto de trabalho, às experiências relativas à pandemia e aos dados demográficos foram tidas como independentes.

### Procedimentos

#### Coleta de dados

A coleta de dados ocorreu entre os meses de junho e julho de 2021. Utilizou-se um formulário eletrônico autoaplicável que foi divulgado através do curso online de aperfeiçoamento em “Tecnologia na Educação, ensino híbrido e inovação pedagógica”, promovido pelo Laboratório Digital Educacional da Universidade Federal do Ceará. Os participantes do curso receberam o formulário através da internet. Inicialmente, os respondentes eram direcionados ao Termo de Consentimento Livre e Esclarecido e, em seguida, eram questionados sobre a anuência em participar do estudo. Somente aqueles que concordaram em colaborar com a investigação eram encaminhados para o questionário propriamente dito. Foram incluídos na amostra somente professores da rede pública que atuavam de forma remota ou híbrida no período da pesquisa.

#### Análise de dados

Foi realizada uma análise de regressão linear múltipla com o objetivo de avaliar os preditores de transtornos mentais comuns. O Software R Studio (versão 2022.12.0) e os pacotes tidyverse (versão 1.3.2), tidymodels (versão 1.0.0), performance (versão 0.10.2), car (versão 3.1-1), olsrr (versão 0.5.3) e sjPlot (2.8.12) foram utilizados para realizar as análises. Foram testados os seguintes pressupostos: ausência de multicolinearidade, independência e normalidade dos resíduos, homocedasticidade de variância não nula.

### Considerações éticas

O projeto foi apreciado pelo Comitê de Ética em Pesquisa da Universidade Estadual\
Vale do Acaraú e autorizado sob o número CAAE 51056621.2.0000.5053, seguindo todas as diretrizes e normas regulamentadoras descritas na resolução CNS 466/12 e 510/2016.

## Resultados

Na amostra, 21,6% dos participantes apresentaram indicativos de TMC’s. Em relação à regressão, os pressupostos de ausência de multicolinearidade (VIF \< 3), independência entre os resíduos (Durbin-Watson = 1,98) e variância não nula (DP \> 0) foram atendidos. Verificou-se, no entanto, que os resíduos não tinham distribuição normal, além de apresentarem heterocedasticidade. Dessa forma, devido à violação desses critérios realizou-se procedimento de bootstrap (1.000 reamostragens), que fornece melhores intervalos de confiança (Efron, 1987).

O modelo de regressão linear se mostrou significativo (F(16, 14357) = 306,5; p \< 0,001; R2 = 0,25). Encontrou-se que as variáveis preditoras de TMCs foram gênero (β = 0,11, p \< 0,001), idade (β = -0,17, p \< 0,001), raça (β = -0,02, p \< 0,01), situação da renda após o início da pandemia da Covid-19 (β = 0,04, p \< 0,001), participação de grupo de risco (β = 0,09, p \< 0,001), recebimento de diagnóstico de Covid-19 (β = 0,04, p \< 0,001), perdas de familiares ou amigos para a Covid-19 (β = 0,05, p \< 0,001), atuação no Ensino Médio (β = 0,03, p \< 0,05) e em mais de um nível de ensino (β = 0,03, p \< 0,01), organização do trabalho (β = 0,29, p \< 0,001), condições de trabalho (β = 0,07, p \< 0,001) e relações socioprofissionais (β = 0,13, p \< 0,001). As variáveis estado civil e renda per capita familiar mensal não foram significativas no modelo.

Apresentaram maiores médias de TMCs docentes que pertenciam ao gênero feminino, que se autodeclararam brancos, que tiveram a renda diminuída após o início da pandemia, que eram do grupo de risco para Covid-19, que foram diagnosticados com Covid-19, que perderam amigos ou familiares para a doença, que atuavam no Ensino Médio ou em mais de um nível de ensino. A idade mostrou uma relação negativa com os TMCs, de modo que participantes mais velhos tinham pontuações menores. As variáveis organização do trabalho, relações socioprofissionais e condições de trabalho apresentaram uma relação positiva com os TMCs, assim piores percepções do contexto laboral implicavam em maiores pontuações nos TMCs.
