# Sobre os autores

**Ana Carolina Borges Leão Martins**

Psicanalista, doutora em Teoria Psicanalítica pela UFRJ. Professora adjunta do departamento de Psicologia da UFC e do Mestrado Profissional em Psicologia e Políticas Públicas UFC \- Sobral. Psicanalista do Coletivo Margem Psicanálise, no qual desenvolve trabalho com clínicas públicas em Fortaleza \- CE.

**Ariadsa Mesquita Aragão**

Psicóloga, graduada pela Universidade Federal do Ceará \- *campus* Sobral. Residente em Saúde da Família pela Escola de Saúde Pública Visconde de Sabóia (EPS \- VS). Ex-bolsista PREX do Núcleo de Estudos e Extensão sobre Subjetivação e Sexualidade (SuSex), vinculado ao curso de Psicologia da Universidade Federal do Ceará \- *campus* Sobral. Ex-extensionista do Laboratório de Estudos das Desigualdades e Diversidades (LAEDDES).

**Camilla Araújo Lopes Vieira**

Psicanalista. Docente da Universidade Federal do Ceará (UFC), *campus* de Sobral. Professora do Mestrado Profissional em Psicologia e Políticas Públicas. Pós-Doutora pela UERJ.

**Eliane Clares Barbosa**

Psicóloga, Mestra em Psicologia e Políticas Públicas pela Universidade Federal do Ceará (UFC). Servidora pública no Centro de Atenção Psicossocial (CAPS) de Quixeramobim-CE. Preceptora da Residência Multiprofissional em Saúde (RESMULTI) da Escola de Saúde Pública do Ceará (ESP-CE). Assessora técnica do Núcleo de Educação Permanente em Saúde (NUMEPS) de Quixeramobim-CE.

**Francisco Pablo Huascar Aragão Pinheiro** 

Psicólogo, Mestre em Psicologia e Doutor em Educação, títulos obtidos pela Universidade Federal do Ceará. Professor do curso de graduação em Psicologia e do Programa de Pós-graduação Profissional em Psicologia e Políticas Públicas do *campus* Sobral da Universidade Federal do Ceará. Bolsista de produtividade em pesquisa da Fundação Cearense de Apoio ao Desenvolvimento Científico e Tecnológico.

**Gracymara Mesquita Severiano**

Mestra em Psicologia e Políticas Públicas pela Universidade Federal do Ceará. Graduada em História pela Universidade Estadual Vale do Acaraú. Professora de História e Projeto de Vida na rede pública de Sobral.

**Haline Maria Parente Rodrigues**

Psicóloga e Mestra em Psicologia e Políticas Públicas, títulos obtidos pela Universidade Federal do Ceará. Especialista em Psicologia Educacional pela UNIQ e Saúde Mental pela FAVENI. Professora e gestora de extensão do curso de graduação em Psicologia do Centro Universitário UNINTA \- Itapipoca.

**Hellen Beatriz Martins Braga**

Graduanda em Psicologia pela Universidade Federal do Ceará – *campus* Sobral (UFC). Membro do Laboratório de Estudos das Desigualdades e Diversidades (LAEDDES), do Laboratório de Clínica, Sujeito e Políticas Públicas (CLIPSUS) e do Núcleo de Estudos e Extensão sobre Subjetivação e Sexualidade (SuSex).

**Hiara da Silva Santos Barbosa**

Psicóloga, graduada pela Universidade Federal do Piauí (UFPI). Mestre em Psicologia e Políticas Públicas pela Universidade Federal do Ceara (UFC). Especialista em Neuropsicologia pela Unichristus. Orientadora educacional da Rede Municipal de ensino de Sobral e Psicóloga Clínica em instituição privada.

**Iratan Bezerra de Sabóia**

Psicólogo, Doutor em Psicologia pelo Programa de Pós-Graduação em Psicologia da Universidade Federal do Ceará. Coordenador do Laboratório de Estudos das Desigualdades e Diversidades (LAEDDES). Professor do Mestrado em Psicologia e Políticas Públicas da Universidade Federal do Ceará – *campus* Sobral.

**Janne Izabel Alves de Sousa**

Psicóloga, Mestra em Psicologia e Políticas Públicas pela Universidade Federal do Ceará. Graduada pelo Centro Universitário Santo Agostinho. Pós-Graduada em Gestão de Pessoas pela Faculdade Estácio e Psicologia Hospitalar pela Faculdade de Enfermagem São Vicente de Paula. Membro da equipe Multiprofissional da APS – eMulti do município de Crateús \- CE. Preceptora de núcleo de psicologia da Saúde da Família pelo Programa de Residência Multiprofissional em Saúde da Escola de Saúde Pública do Ceará.

**Jocélia Maria Santos de Lira Pessoa**

Psicóloga, Mestra em Psicologia, título obtido pela Universidade Federal do Ceará. Orientadora Educacional da Prefeitura Municipal de Sobral.

**Juliana Maria do Nascimento Mota**

Graduada em Psicologia pela Universidade Federal do Ceará – *campus* de Sobral (UFC). Mestra em Psicologia pelo Programa de Pós-Graduação Profissional em Psicologia e Políticas Públicas \- UFC/Sobral. Especialista em Psicologia Educacional pela Faculdade de Quixeramobim – UNIQ e em Gênero, Diversidade e Direitos Humanos pela Universidade da Integração Internacional da Lusofonia Afro-Brasileira – UNILAB. Professora substituta no curso de Psicologia da Universidade Federal do Ceará – *campus* Sobral.

**Juliana Vieira Sampaio**

Docente em exercício provisório do Departamento de Psicologia da Universidade Federal de Minas Gerais. Docente do Programa de Pós-Graduação Profissional em Psicologia e Políticas Públicas da Universidade Federal do Ceará. Docente do Programa de Pós-Graduação em Psicologia da UFMG. Pós-doutora em Psicologia (2019-2020) pela Universidade Federal do Ceará, Doutora em Psicologia pela Universidade Federal de Pernambuco (2014 \- 2016).

**Maiara Braga Nascimento**

Graduanda em Psicologia pela Universidade Federal do Ceará – *campus* Sobral (UFC). Membro do Laboratório de Psicologia Histórico-Cultural (LAPSIHC), do Laboratório de Estudos das Desigualdades e Diversidades (LAEDDES) e bolsista do Projeto de Extensão Entre Muros.

**Marcos Daniel Canuto Alves**

Graduando em Psicologia pela Universidade Federal do Ceará – *Campus* de Sobral (UFC). Membro do Laboratório de Estudos das Desigualdades e Diversidades (LAEDDES) e do Núcleo de Estudos e Extensão sobre Subjetivação e Sexualidade (SuSex).

**Natalia Santos Marques**

Psicóloga, Mestra em Teoria e Pesquisa do Comportamento pela Universidade Federal do Pará e Doutora em Psicologia Experimental pela Universidade de São Paulo. Professora do curso de graduação em Psicologia e do Programa de Pós-graduação Profissional em Psicologia e Políticas Públicas do *campus* Sobral da Universidade Federal do Ceará.

**Rita Helena Sousa Ferreira Gomes**

Graduada (Universidade Estadual do Ceará), Mestra e Doutora em Filosofia (Universidade Federal de Minas Gerais). Professora titular da UFC – *campus* Sobral, responsável pelo setor de estudos ‘Filosofia Geral’. Professora do Programa de Pós-graduação Profissional em Psicologia e Políticas Públicas do *campus* Sobral da Universidade Federal do Ceará e do Mestrado Profissional em Artes (PROFARTES).

**Thamyles de Sousa e Silva**

Mestranda no Programa de Pós-Graduação em Psicologia e Políticas Públicas da Universidade Federal do Ceará – *campus* Sobral. Especialista em Saúde Pública e da Família pela Faculdade de Quixeramobim – UNIQ. Psicóloga pelo Centro Universitário INTA (UNINTA). Preceptora no curso de Psicologia do UNINTA e docente no curso de Psicologia da Faculdade de Sobral – FASOL.

**Vanessa Cunha Santiago**

Psicóloga, Psicanalista, Mestra em Psicologia e Políticas Públicas pela Universidade Federal do Ceará \- *campus* Sobral. Professora do Ensino Superior nas áreas de Psicologia da Educação

**Vera Silvia Paula Pessoa Aguiar Neta**

Graduanda em Psicologia pela Universidade Federal do Ceará – *campus* Sobral. Bolsista do Programa de Educação Tutorial (PET). Extensionista voluntária do Laboratório de Estudos das Desigualdades e Diversidades (LAEDDES), do Projeto Mini Cientista, do Programa de Educação pelo Trabalho para a Saúde – PET Saúde/Equidade e do Projeto Saúde Mental e Feminismos.
