---
author: 
  - name: Roberta de Fátima Rocha Sousa
    url: http://lattes.cnpq.br/3212189083748734
    orcid: 0009-0003-1182-6916 
    email: robertafrsousa@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Juliana Vieira Sampaio
    url: http://lattes.cnpq.br/9556200287516417
    orcid: 0000-0001-5770-244X 
    email: julianavsampaio@hotmail.com 
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: sousa_violencia.bib
reference-section-title: Referências
---

# “Do meu jeito, fiz a minha revolução”: as diversas camadas da violência contra a mulher que se prostitui

## Introdução

> “Do meu jeito, fiz a minha revolução e fui em frente” [@leite2009filha, p. 31]

Pensar a invisibilidade, ou mesmo a invisibilização, da prostituição enquanto estigma e, principalmente, da mulher que se prostitui é essencial para construir novas formas de cuidado e atenção em políticas públicas para esse grupo populacional. Mesmo diante dos discursos repetitivos de que a prostituição é a profissão mais antiga do mundo, olha-se mais para o ato de prostituir-se do que para as mulheres que exercem essa profissão, as quais, de acordo com Grant [-@grant2021dando], são percebidas como uma mulher invisível, sem voz, oculta, mesmo com sua nudez em público.

Olhar esse fenômeno a partir da Psicologia permite-nos a compreensão das implicações no que se diz respeito aos modos de vida e de significação das subjetividades dessas mulheres, problematizando as agressões simbólicas e físicas, os processos de silenciamento e estigmatização, os modos de sociabilização e enfrentamento [@silva2014implicacoes]. Nesse contexto, apostamos na possibilidade de produzir um olhar mais sensível para essas questões, assim como de construir transformações no campo acadêmico a partir da inserção da pesquisadora. Estudos e pesquisas acerca dessa temática dentro da Psicologia são relativamente recentes, o que torna esta pesquisa ainda mais potente.

Pensamos o nosso percurso a partir da noção de Psicologia Andarilha, em que caminhamos no ritmo dos acontecimentos, de forma que uma prática andarilha considera as circunstâncias do campo. Pretendeu-se construir a pesquisa junto às mulheres, respeitando as singularidades e subjetividades destas. De acordo com Quadros [-@quadros2023experiencias], a Psicologia Andarilha é aquela que também vai acompanhar as pessoas em suas mobilidades, ou seja, aquela que caminha junto, desloca-se, sai do lugar, dando novos sentidos. De acordo com o dicionário eletrônico Michaelis [-@michaelis2024andarilho], andarilho é “aquele que caminha bastante; que caminha ou anda muito”. Essa metáfora amplia um modo de pensar a Psicologia, ao passo que, em nossa práxis, somos andarilhos, caminhamos por terras diferentes, em diversos momentos, sob o risco da errância e, ao mesmo tempo, das surpresas de boas descobertas.

Ao pensarmos, a partir de uma Psicologia Andarilha, o caminhar por terras diferentes, explorando espaços e construindo caminhos possíveis, como aponta Quadros [-@quadros2023experiencias], compreendemos que ainda temos muito a fazer nesse lugar, percebendo que aquilo que nos atravessa e nos mobiliza se torna nosso também. Entendemos o andar como uma convocação do campo, não se tratando de um fazer para, mas de um fazer com, são possibilidades de caminhos que a Psicologia Andarilha nos permite percorrer. Pensar na dimensão de pesquisar as violências sofridas por essas mulheres é saber que elas não estarão nos esperando, assim como não terão muito tempo disponível para estar conosco, requerendo da pesquisadora um maior ajuste nesse território, respeitando as dinâmicas que o campo apresenta. Entendemos que esta pesquisa pode contribuir para uma maior aproximação e um maior incentivo da Psicologia em debater este tema e produzir novas práticas pautadas no acolhimento, na promoção de saúde e no cuidado amplo a essas mulheres. Segundo Maia *et al*. [-@maia2002profissionais], no cotidiano das mulheres que se prostituem estão presentes aspectos como violência e agressão física por parte dos clientes, conflito com a polícia, ocultação da profissão em face de familiares e amigos, além do conflito moral com a prática do sexo comercial.

A partir desse cenário de inquietações que vêm desde a graduação é que surge o interesse em estudar as violências sofridas por essas mulheres, sendo importante mostrar/escancarar, tornar o invisível visível; de alguma forma é mexer na estrutura daquilo que é posto enquanto norma, mesmo que de forma simbólica. O corpo da mulher que se prostitui é tido como de domínio público. Conforme Butler [-@butler2015quadros], algumas vidas são vistas como menos dignas, e a elas são distribuídas diferencialmente proteção e violência, demarcando, assim, quais vidas importam e quais não.

Justificamos a relevância desta pesquisa pela necessidade de ampliar o escopo acadêmico sobre a realidade das profissionais do sexo, especialmente no que se refere ao território do interior do Ceará. Em busca nas bases de dados da Plataforma CAPES e da Biblioteca Virtual em Saúde (BVS), foram encontrados apenas 03 artigos sobre a prostituição na cidade de Sobral/CE, referente aos anos de 2007, 2008 e 2013. Dessa forma, esperamos que esta pesquisa possa servir de ponto de partida para outros estudos e de desenvolvimento de novas práticas de cuidados para essas mulheres.

Explanamos, neste texto, um recorte dos resultados de uma pesquisa de mestrado, de visitas institucionais realizadas e de entrevista realizada com a liderança do movimento das profissionais do sexo da cidade. Partindo de tais vivências, estabelecemos como objetivo principal deste estudo analisar as diferentes vivências de violência sofridas pelas profissionais do sexo.

## Parcerias que sustentam a pisada no campo

A execução desta pesquisa só foi possível a partir das parcerias que proporcionaram a inserção no campo, bem como a união do mestrado com a extensão universitária. Essas parcerias não só proporcionaram um maior suporte às atividades realizadas, como também aumentaram as possibilidades de intervenções com as mulheres. Sendo assim, neste tópico, apresentamos as parcerias que possibilitaram a realização desses encontros.

### SUSEX

O Núcleo de Estudos e Extensão sobre Subjetivação e Sexualidade (SUSEX) é um projeto que está vinculado ao curso de Psicologia da Universidade Federal do Ceará, *campus* Sobral. Tendo como objetivo principal a promoção da equidade de gênero e do respeito à diversidade sexual, busca promover resistência, por meio da potência criativa, indo contra a homogeneização e padronização dos modos de viver.

Nesse sentido, o SUSEX procura realizar atividades de ensino, pesquisa e extensão que estejam em diálogo com discentes da graduação e da pós-graduação, além da participação da comunidade externa à universidade, desenvolvendo ações voltadas, principalmente, para a promoção de direitos e saúde sexual e reprodutiva, além de outras atividades relacionadas às discussões de gênero e sexualidade.

### Astras[^sousa_violencia-1]

[^sousa_violencia-1]: As informações desse tópico são provenientes do podcast disponível em: https://open.spotify.com/episode/7bxxM2TzxqutZghrAp9NBF?si=8ea52faf26de475a

A Associação Sobralense das Trabalhadoras do Sexo (ASTRAS) apresentou seus primeiros passos no ano de 1999, sendo registrada no ano 2000. Trata-se de uma ONG com o objetivo de trabalhar com os direitos e as defesas das mulheres que se prostituem, a partir de parcerias e recursos, para a prevenção do HIV e de outras ISTs na cidade de Sobral/Ce. É válido ressaltar que, nesse período, não havia nenhum trabalho desenvolvido por entidades ou serviços de saúde direcionado ao público de profissionais do sexo, com finalidade de prestação de serviço ou psicoeducação de orientação sobre temáticas relacionadas à vida sexual saudável, sem infecções.

Desse modo, após a identificação da necessidade de locais para atender à demanda dessas mulheres e construir espaços, deu-se início à criação da ASTRAS. Pretendia-se, inicialmente, entender as especificidades dessas mulheres, de modo a fazer busca ativa acerca do estilo de vida delas e viabilizar o acesso aos serviços de saúde do município, uma vez que esses locais eram limitados em decorrência do preconceito sofrido.

Com o apoio da Escola de Saúde da Família, foi realizada a busca ativa, a qual citamos anteriormente, para cadastrar tanto as casas de prostituição como as suas donas e as profissionais que nelas trabalhavam. A princípio, os atendimentos eram realizados nas casas de prostituição. Depois de uma maior aproximação com o serviço, que na época era feito pelo Coas – Centro de Orientação e Aconselhamento Sorológico, eram realizados os encaminhamentos. Posteriormente, foram realizadas parcerias com os postos de saúde dos bairros, para um melhor direcionamento dos encaminhamentos e atendimentos. Nos casos de aborto, por vezes, as equipes se deslocavam até as mulheres para levá-las para a Santa Casa de Misericórdia de Sobral.

Durante o processo de implementação da ASTRAS, pôde-se evidenciar a resistência para acessar os cabarés e iniciar o trabalho de reconhecimento dessas mulheres para além do estigma, compreendendo-as em sua totalidade como mães, mulheres, filhas, companheiras, e não apenas profissionais do sexo. A mulher que protagonizou a criação da ASTRAS[^sousa_violencia-2], atualmente, não se encontra mais à frente da associação.

[^sousa_violencia-2]: Em visita à ASTRAS, foi-nos comunicado que o local em que a associação funcionava precisou ser entregue, pois, diante da ausência do repasse da Secretaria de Saúde do município de Sobral/Ce, ficou inviável manter as despesas de aluguel, água e luz. Atualmente, a associação foi acolhida pela Casa Madre Anna Rosa Gattorno, servindo de ponto de apoio para as atividades com as profissionais do sexo.

Com o intuito de manter o sigilo da sua identidade, chamamos de Girassol a mulher que esteve presente quando a associação foi criada. Girassol, na época manicure e costureira, morava bem próximo às casas de prostituição. Assim, além de fazer as unhas das prostitutas, também costurava para elas. Girassol se tornou uma figura de cuidado: durante o serviço de manicure e costura, também ouvia os relatos de sofrimento e dificuldade do trabalho na prostituição. Tornou-se, dessa forma, uma rede de apoio para elas, uma vez que existia uma relação de confiança.

## Percurso metodológico

Esta é uma pesquisa de natureza qualitativa, tal metodologia foi escolhida por entendermos que ela contribui para a compreensão dos aspectos sociais e subjetivos em diferentes práticas na nossa sociedade. Utilizamos, como referencial teórico metodológico, a pesquisa-intervenção-implicação, que, de acordo com Romagnoli [-@romagnoli2014conceito], “ocorre quando há a irrupção do plano das forças que se conectam nos encontros ‘entre’ o pesquisador e seu objeto de estudo” (p. 49). Essa prática dá mais potência ao processo de pesquisar, pois também se trata de o pesquisador ter abertura para o campo.

De acordo com Aguiar e Rocha [-@aguiar2007micropolitica], nessa perspectiva, o conceito de implicação está ligado à capacidade de fazer conexões, de fazer deslocamentos que nos levam a considerar novas invenções. Essa perspectiva de fazer pesquisa é essencial, pois estivemos no cotidiano com as profissionais do sexo não apenas ouvindo suas narrativas, mas também participando/intervindo de forma implicada para promoção de melhores condições de vida.

Nessa concepção, pensar pesquisa do tipo pesquisa-intervenção, em Psicologia, segundo Cavalcante [-@cavalcante2016sobre], é aceitar o convite ao deslocamento e à autocrítica do próprio campo da Psicologia. Partindo de alternativas participativas que nos distanciam dos falaciosos ideais de neutralidade, de forma que possamos entender esse tipo de pesquisa como uma ferramenta a partir da qual ação não se faz *sobre*, mas *com* grupos subalternos, este pesquisar produz efeito ainda enquanto é feito, tratando-se de fazer pesquisa junto e não para.

Sobre a pesquisa qualitativa, Godoy [-@godoy1995introducao] afirma que, a partir dela, um fenômeno pode ser mais bem compreendido no contexto que ocorre, assim como a análise pode ser realizada em uma perspectiva integrada. Sendo assim, a pesquisa qualitativa permite essa maior aproximação do pesquisador com o sujeito a ser estudado dentro do seu contexto, compreendendo esse sujeito dentro de uma integralidade e possibilitando intervenções a partir dos vividos em campo. Entende-se que, no fazer pesquisa, não há neutralidade, uma vez que o pesquisador é atravessado por afetos, assim como afeta também. Sobre a inserção do pesquisado:

> O pesquisador qualitativo reflete sistematicamente sobre quem é ele na investigação e é sensível à sua biografia pessoal e à maneira como ela molda o estudo. Essa introspecção e esse reconhecimento de vieses, valores e interesses (ou refletividade) tipifica a pesquisa qualitativa atualmente. O eu pessoal torna-se inseparável do eu pesquisador. Isso também representa honestidade e abertura para pesquisa, reconhecendo que toda investigação é carregada de valores [@creswell2007projeto, p. 187].

Ao pensarmos nas relações de afetos e confiança – as quais são construídas e estabelecidas a partir desses lugares para que possamos compreender que falamos de mulheres que carregam estigmas e são rotuladas –, percebemos a importância de não impor normas ou trabalhar conceitos entre certo e errado. Nosso objetivo é respeitar a singularidade e subjetividade de cada uma, criando espaços de construção de afetos nos quais elas possam se expressar livremente, sem julgamentos.

Utilizamos, também, na nossa pesquisa, a estratégia metodológica da observação participante, pois essa abordagem vai além da simples observação, envolvendo um conjunto diversificado de técnicas metodológicas que demandam um profundo envolvimento da pesquisadora com a situação estudada. Além disso, Ludke [-@ludke1986pesquisa] sugere que o relato das observações deve transcender a mera descrição, incorporando uma dimensão reflexiva. Nesse sentido, a pesquisadora é encorajada a incluir observações pessoais, especulações, sentimentos, problemas, impressões, dúvidas, incertezas, surpresas e decepções em sua narrativa.

### Local

Sobral é um município no interior do Ceará, com uma população de 210.711 habitantes, conforme estimativa do IBGE (Instituto Brasileiro de Geografia e Estatística) de 2020. De acordo com o IDH (Índice de Desenvolvimento Humano), é o 5º município mais povoado e o segundo mais desenvolvido do estado do Ceará. A pesquisa aconteceu na cidade de Sobral/Ce, nos seguintes locais: casa de prostituição localizada no mercado central e Casa Madre Anna Rosa Gattorno, situadas no bairro Sinhá Sabóia.

### Coleta de dados

Apresentamos aqui um recorte de uma pesquisa de mestrado. Foram realizadas 03 (três) visitas institucionais (ASTRAS, CMC e CRIS), que tiveram o objetivo de conhecer o funcionamento e fluxo da profissional do sexo, assim como verificar estatísticas de violência contra elas. Por fim, realizamos uma entrevista semiestruturada com a liderança das Astras, com intuito de ter uma maior compreensão da importância da associação para as profissionais do sexo, como também conhecer os impactos das ausências de políticas públicas direcionadas para essas mulheres.

Ludke [-@ludke1986pesquisa] enfatiza que registrar essas experiências por meio da escrita é uma forma importante de possibilitar que as pessoas na sociedade tenham acesso e compreendam diferentes questões, especialmente em um mundo atual em que a tecnologia da informação desempenha um papel significativo. Kroeff *et al*. [-@kroeff2020diario] trazem que a realização do trabalho de campo é uma estratégia essencial na pesquisa, pois integra proposições teóricas à experiência prática na construção de conhecimento contextualizado. Em muitos estudos exploratórios qualitativos, especialmente em áreas da Psicologia, a prática comum é empregar diários de campo como uma ferramenta metodológica. Esses diários são utilizados para registrar e posteriormente analisar a experiência tanto da pesquisadora quanto dos participantes. No contexto da pesquisa, os diários de campo foram uma ferramenta usada para documentar e comunicar essas experiências, tornando-as mais acessíveis e compreensíveis para um público mais amplo.

Dessa forma, selecionamos a escrita de diários de campo como uma estratégia valiosa para a produção e análise da interação da pesquisadora com o tema do campo de pesquisa. Isso ocorre por meio da problematização da memória, do hábito e da criação de uma atenção direcionada para modular a experiência tanto da pesquisadora quanto do mundo ao seu redor. Ressaltamos que os diários de campo foram utilizados em todas as etapas da pesquisa.

Além do diário de campo, como instrumento de coleta de dados para a composição desta pesquisa foi aplicado 01 (um) questionário socioeconômico e 01 (uma) entrevista semiestruturada, a qual foi gravada e posteriormente transcrita, com a liderança da ASTRAS. Segundo Manzine [-@manzine2004entrevista], a entrevista tem como principal característica um roteiro com perguntas abertas, sendo indicada para estudar um fenômeno com uma população específica. Cumpre destacar a importância dessa entrevista, uma vez que a liderança nos transmitiu, ao longo deste estudo, as dificuldades existentes no campo das políticas públicas assim como a própria mediação com o campo.

Vale ressaltar que, no projeto original, se tinha a pretensão de entrevistar 05 (cinco) mulheres, mas conseguimos entrevistar apenas a liderança da ASTRAS, uma vez que o campo não estava propício para realizar as demais entrevistas.

Foram diversas tentativas de contato que aconteceram entre o período de fevereiro e junho/24, tanto por mensagens de WhatsApp quanto por ligação, as quais tiveram o objetivo de marcar a entrevista, de forma que conseguimos 05 (cinco) confirmações. Quando elas não compareciam, a liderança da ASTRAS entrava em contato para informar. Ainda na tentativa de conseguir realizar as entrevistas, fizemos contato com a dona da casa de prostituição, a qual nos informou que falaria com o marido para saber o que achava, tendo sido esse o último contato. Nenhuma das interlocutoras respondia às mensagens ou atendia mais as ligações, o que causou certa angústia, uma vez que não conseguiríamos fazer a coleta de dados pretendida.

Compreendendo e respeitando o fechamento do campo diante da ausência de possibilidades para continuar, deparamo-nos com reflexões do quanto esse campo necessita de permanência, pois, enquanto estávamos presentes, foi possível sentir as diversas possibilidades que emergiam. Precisamos, à certa altura, nos afastar para aguardar o parecer do comitê de ética. Sobre isso, ficou evidente o quanto o afastamento foi prejudicial, retornar foi como voltar ao início. Assim, diante do exposto, ficamos com o que o campo nos permitiu acessar, realizamos apenas uma entrevista com a liderança à título de documentação, a qual utilizamos para a composição desta pesquisa. Cumpre ressaltar que a entrevistada assinou o Termo de Consentimento Livre Esclarecido (TCLE).

### Análise dos dados

Para análise dos dados, utilizamos a abordagem teórico-metodológica da noção de práticas discursivas e produção de sentidos. Quando relacionamos práticas discursivas com produção de sentidos, assumimos que os sentidos não estão na linguagem enquanto materialidade, mas no discurso, que transforma a linguagem enquanto ferramenta de construção da realidade. No caso do relato, a ação de relatar é, de fato, explicativa na sua relação com o contexto. Como Spink e Lima [-@spink2013rigor] apontam, no relato, o foco é o que o sujeito narra, os argumentos utilizados, assim como a explicação dada para validar a narrativa.

Para a análise de dados, utilizamos o recurso de mapas de associação de ideias, os quais, de acordo com Spink e Lima [-@spink2013rigor], têm por objetivo sistematizar o processo de análise das práticas discursivas na busca dos aspectos formais tanto da construção linguística, quanto dos repertórios utilizados nessa construção. Ademais, são considerados instrumentos com duplo objetivo: fornecer subsídios ao processo de interpretação e facilitar a comunicação dos passos subjacentes ao processo interpretativo.

### Aspectos éticos

Esta pesquisa foi submetida ao comitê de ética em pesquisa com seres humanos, seguindo as Diretrizes e Normas Regulamentadoras de Pesquisa Envolvendo Seres Humanos, segundo Resolução 466/12 do Conselho Nacional de Saúde. Isso se deu de forma que foi respeitada a voluntariedade da participante. Ela não recebeu e nem pagou para fazer parte desta pesquisa. Também lhe foi garantido o sigilo e o anonimato. Foram-lhe explicados os objetivos da pesquisa, assegurando à entrevistada a possibilidade de interromper a participação a qualquer momento, sem prejuízo algum [@brasil2012resolucao]. A participação, nesta pesquisa, foi efetivada por meio da assinatura do Termo de Consentimento Livre e Esclarecimento (TCLE), tendo como parecer favorável o Parecer n.º 6.662.189, de 21 de fevereiro de 2024.

## Visitas institucionais

### Astras e casa de prostituição

Foram realizadas duas visitas à Casa Madre Anna Rosa Gattorno, que serão descritas posteriormente. Essas visitas tiveram o intuito de conhecer o funcionamento e o fluxo da ASTRAS.

Na segunda visita à ASTRAS, que aconteceu em abril de 2023, a pesquisadora foi convidada para conhecer uma das casas de prostituição situada nos arredores do mercado central da cidade de Sobral/Ce. É importante mencionar que esse foi o primeiro contato com o local, bem como não havia sido cogitada a possibilidade dessa visita acontecer nesse referido dia, de forma que, movida pelo desejo de adentrar no campo, o convite foi aceito. Na referida ocasião, a liderança passou algumas instruções do tipo: como agir em caso de abordagem de algum homem; e, caso acontecesse, lembrar que estávamos no ambiente deles, portanto, deve-se responder com firmeza sem ser agressiva. Sendo assim, recorremos ao diário de campo com o intuito de relatar os experienciados nessa ocasião:

> Chegamos... a entrada era de um bar comum, com poucas mesas, umas 03 (três) mulheres bebendo em uma das mesas na entrada, um cara meio mal-encarado na porta, no primeiro momento pensei ser um cliente, mas depois imaginei que pudesse ser uma espécie de segurança, pois ele ficou o tempo todo no mesmo lugar (Diário de campo 24/04/23).

Fomos apresentadas a uma mulher, a responsável pelo local, que nos convidou para conhecer tanto o seu estabelecimento quanto a casa de prostituição que fica ao lado. Sobre a primeira casa:

> Vi o quanto era grande, tinham várias mesas, cadeiras e um corredor com várias portas, olhei bem rápido, pois tinham umas mulheres lá, e não queria que elas achassem que eu as observava, também tinha nesse espaço uma caixa grande, que acredito ser aquelas que as pessoas colocam moedas e escolhem as músicas (jukebox) (Diário de Campo, 24/04/23).

A segunda casa era separada da primeira por um comércio que tinha uma entrada bem estreita. Lá, muitos homens estavam bebendo. Minha primeira impressão foi tratar-se apenas de um bar.

> Fui entrando, cumprimentando e, com meio sorriso, não sabia como me comportar, mas tentando ao máximo não fazer contato visual. Tinha um mundo grande, muita gente, acho que todas as mesas estavam ocupadas, um corredor cheio de portas e ao final uma cozinha que estava separada por uma grade (Diário de campo, 24/04/23).

> Quando estávamos saindo, fomos abordadas por uma das mulheres perguntando sobre a coleta de exames (Diário de campo, 24/04/23).

Percebemos a importância de mencionar essa fala, uma vez que ela apresenta uma conscientização da importância do cuidado à saúde e uma busca por essa política pública. Percebemos, nas visitas à ASTRAS, nos diálogos com a liderança e nessa visita à casa de prostituição, que as profissionais do sexo não acessavam os dispositivos de saúde, o que na ocasião chamou nossa atenção. Os estigmas sociais e julgamentos morais dos profissionais da saúde podem, muitas vezes, afastar essas mulheres dos serviços. Corroborando Maciel *et al*. [-@maciel2020percepcoes], é de extrema importância que os profissionais de qualquer política pública, e não apenas da saúde, estejam capacitados para acolher e fazer os devidos encaminhamentos e as orientações de forma humanizada e acolhedora às profissionais do sexo. Tendo em vista que esse foi o primeiro contato com o campo, foi um momento de muita potência e atravessamento, um sentir/encarnar aquilo que antes era apenas teoria: virou vivência.

### Casa da Mulher Cearense (CMC) e Centro de Referência em Infectologia (CRIS)

Com intuito de conhecer as políticas públicas destinadas à proteção e à prevenção de violência contra a mulher e a atuação frente às Infecções Sexualmente Transmissíveis (IST) e HIV/Aids, visitamos a CMC e o CRIS.

Em abril de 2023, visitamos a Casa da Mulher Cearense. Ao chegar ao dispositivo, enquanto esperávamos para conversar com a responsável pela instituição, conversamos com a recepcionista, que brevemente nos explicou a proposta do equipamento. Em seguida, a pesquisadora foi recebida e explicou sobre o intuito da visita, a interlocutora esboçou alegria com a apresentação, observando “grupo invisível”[^sousa_violencia-3] e seguiu nos dizendo que a casa não tinha demanda de profissionais do sexo, mas que consultaria o setor psicossocial para ter mais certeza.

[^sousa_violencia-3]: Expressão utilizada pela responsável da CMC.

> Me senti constrangida pela forma com que ela falava em tom de autoridade e julgamento e acabei nem fazendo as perguntas que tinha planejado, parti para suposições. Perguntei se a profissional do sexo procurasse a casa sob demanda de violência, ela nos respondeu que era feito encaminhamento para a DDM, e mesmo que realizassem esse atendimento, elas não registravam, a não ser que essa mulher fizesse questão de ser ouvida é que abririam o prontuário (Diário de Campo, 25/04/23).

Uma fala que reforça ainda mais a invisibilização, um não querer ver. Prada [-@prada2018putafeminista] afirma que “nunca uma mulher como as outras, a prostituta está além da fronteira, lá onde as mulheres ditas decentes não podem estar. E é ela, somente ela que a sociedade escolhe condenar e apedrejar” (p. 35). Como ouvido e sentido, como um julgamento, sentença final, uma fala que traz um não merecimento de proteção, a não ser que ela faça “questão”.

Cada vez mais vamos compreendendo que um dispositivo feito para mulheres não pensa em todas as possibilidades de mulheridades, ou seja, algumas mulheres têm acolhimento, atendimento necessário e possíveis encaminhamentos, mas, se falamos da profissional do sexo, a atuação é outra. Já é sabido que a Lei Maria da Penha não abarca as violências sofridas pelas profissionais do sexo, mas, como visto nessa visita, faz-se necessária uma ampliação nos modos de cuidado, pois é um dispositivo para mulheres. Assim, compreendemos que todas elas podem ter acesso, mas, como visto, não só a profissional do sexo não o acessa, como também o referido dispositivo não está aberto para ela. Por fim, conversamos sobre nosso desejo de tornar as profissionais do sexo visíveis em nível de município e fomos surpreendidas mais uma vez pela fala:

> Elas preferem ser invisíveis, pois talvez seja uma forma delas se protegerem. Ali eu já tinha entendido que a profissional do sexo não tinha lugar naquela casa (Diário de Campo, 25/04/23).

No mês de março de 2023, visitamos o CRIS, já com um pouco de receio, pois, quando foi realizado o agendamento da visita, o funcionário que me atendeu foi muito grosseiro e, quando ouviu a expressão prostituta, interrompeu a fala dizendo que não se usava esse termo por ser pejorativo e que eu deveria estudar para não falar besteira, tentei explicar a ele que o termo não estava errado, momento em que ele aumentou o tom de voz, e eu calei.

> Me senti totalmente angustiada após essa ligação, pois me senti agredida, silenciada, mesmo me identificando enquanto pesquisadora, fiquei pensando como essas mulheres acessam esse espaço se ela diz que é prostituta e ela escuta que não é (Diário de Campo, 05/04/23).

Gabriela Leite [-@leite2009filha] afirma que mudar o nome prostituta para profissional do sexo ou trabalhadora do sexo seria como um pedido de desculpas, e, para esse movimento, é de fundamental importância assumir o nome dele e não fugir.

Fomos recebidas pela responsável, a quem explicamos o motivo da visita: verificar se a profissional do sexo acessava o serviço e se era possível obter uma estatística desse acesso. Foi-nos informado que, mesmo que elas se autodeclarassem como tal, só tinha como saber se olhassem os prontuários um a um, pois, na ocasião em que foi realizada uma busca rápida no sistema pelos termos profissional do sexo, prostituta, garota de programa, violência de trabalho, não havia nenhum dado. Inclusive no próprio sistema não consta profissional do sexo enquanto ocupação, vale ressaltar que, na ficha de notificação, já no seu enunciado, só se reconhece como violência a doméstica/intrafamiliar. Assim, os casos de violência extrafamiliar/comunitária incluem apenas: crianças, adolescentes, mulheres, pessoas idosas, pessoas com deficiência, pessoa com transtorno, indígenas e população LGBT. Isso se dá de forma que, ao analisar a ficha de notificação, percebemos que ela não inclui diretamente a profissional do sexo, cabendo à pessoa que irá fazer o seu preenchimento essa pergunta de uma forma mais direta. Porém, é preciso muita sensibilidade para estar inclusive nesse acolhimento, pois, como visto, essa mulher dificilmente busca por esse dispositivo.

> Por várias vezes, ela disse que minha pesquisa era muito difícil, que ia ser muito difícil achar dados, mesmo eu explicando que minha pesquisa não dependia deles. Em seguida, ela perguntou se eu já havia defendido, respondi que não, e disse por que eu não mudava minha pesquisa, pois seria muito difícil. Eu nem acreditei no que ouvi, apenas respondi que era porque era difícil que eu ia continuar pesquisando (Diário de Campo, 02/05/23).

Diante desse fato, compreendemos que, mesmo que a profissional do sexo acesse esse dispositivo, não existem estatísticas desse acesso. Também foi possível observar a inquietação da pessoa com quem conversamos, uma vez que ela não conseguia responder a nossas perguntas. Por fim, mais uma vez, falou sobre a dificuldade de análise de todos os prontuários, os quais somam mais de 35 mil, na tentativa de chegar a um número. Ela relatou que as ações com as profissionais do sexo só acontecem quando elas são solicitadas; e, como o CRIS atende a 55 municípios, não tem como dar conta desse público.

Identificamos a ausência de estatísticas em Sobral sobre as violências sofridas pelas profissionais do sexo e a assistência em saúde, uma vez que temos na cidade os referidos dispositivos, mas estes não possuem esses dados. Significa dizer que temos um dado alarmante, uma vez que não se tem registros de passagem de profissionais do sexo nessas políticas públicas. Como afirma Ribeiro [-@ribeiro2019quem], se uma realidade não é nomeada, sequer serão pensadas melhorias para uma realidade que é invisível.

O que se evidencia a partir dessas visitas é de fato curioso, uma vez que estamos falando de dispositivos em que o primeiro é procurado pela mulher vítima de violência e o segundo atua na prevenção das ISTs (a exemplo do HIV). Isso nos impulsiona a questionarmos o porquê de o município não olhar para essas mulheres. É sabido que temos a lei Maria da Penha, porém temos ciência também de que ela não atende à profissional do sexo.

> Hoje em dia, elas já sabem que tem a lei Maria da Penha, elas já sabem, quando elas sofrem elas vão, mas elas vão como mulher, e não como trabalhadora do sexo, e poucas vão (Entrevista Liderança, 27/03/24).

Sendo assim, percebe-se que a violência contra a mulher, em especial aquela que se prostitui, foi (é) normalizada, tendo em vista os estigmas que esse fazer carrega, colocando-a, assim, em situação de diversas vulnerabilidades: violência de gênero, racial, familiar, discriminação, instabilidade financeira, pobreza e riscos para saúde. Podemos olhar para esses recortes, a partir da interseccionalidade, como uma encruzilhada que vai formando uma rede de muitas camadas de desigualdades. Para Akotirene [-@akotirene2022interseccionalidade], “o pensamento interseccional nos leva a reconhecer a possibilidade de sermos oprimidas e de colaborarmos com as violências” (p. 45).

Mesmo com a construção de políticas públicas para mulheres, estas não assistem todas as mulheres de forma semelhante. O Atlas da violência de 2022, publicado pelo IPEA (Instituto de Pesquisa Econômica Aplicada), apresenta estatísticas sobre a violência contra a mulher como feminicídio da mulher negra, violência urbana/fora da residência, violência (física, psicológica, tortura) contra a população LGBTQIAPN+, porém não se tem estatísticas sobre a violência contra a mulher que se prostitui.

Tais fatores denunciam que a violência contra a prostituta é invisível, uma vez que não têm dados estatísticos sobre ela, assim como políticas públicas específicas, ressaltando que estas só são citadas nas políticas de controle às ISTs. Silva e Ximenes [-@silva2017not] dizem que a violência contra a prostituta se encontra velada no universo da violência de gênero. É preciso compreender as nuances que a violência pode ter para além do que podemos encontrar no senso comum, uma vez que se pode perceber uma naturalização desse fenômeno. Ser mulher, na nossa sociedade, já é uma situação de vulnerabilidade, devido às relações de desigualdade em que a mulher é vista como submissa e inferior aos homens.

## Entrevista liderança da Astras

A entrevista com a liderança da ASTRAS aconteceu no dia 27 de março de 24. Teve uma duração de 27 minutos, sendo gravada e transcrita posteriormente. Falamos sobre a importância da associação, pois, como já visto até aqui, as mulheres não acessam os dispositivos das políticas públicas. Assim, a Associação atua como mediadora, realizando encaminhamentos para exames, distribuindo preservativos e promovendo ações voltadas para as profissionais do sexo. No entanto, a associação está em fase de encerramento de suas atividades, uma vez que a secretaria de saúde cancelou a verba que era destinada para sua manutenção.

> O pior golpe que a Astras sofreu foi nesse atual governo, de retirar uma mísera parcela de contribuição de mil reais, que era o que sustentava a casa pelo menos pra gente ter uma sede, que sem sede não se tem projetos, a gente não pode avançar. Eu não posso fazer um projeto para a secretaria de saúde, eu não posso fazer um projeto pra Alemanha ou qualquer outra instituição que trabalhe com esse público, porque nós não temos sede. Por que que não temos sede? Por que não temos dinheiro pra pagar o aluguel? Não é justo que uma pessoa que trabalhe voluntariamente ainda tenha que tirar do seu bolso para pagar pra poder Sobral dizer ‘ah!, temos uma política’, não temos política nenhuma, nenhuma (Liderança Astras).

Ao acessar esse campo, percebe-se a importância da ASTRAS para essas mulheres. Mesmo que as profissionais do sexo não procurem a Associação, esta vai até elas. Em vários momentos, percebi essa relevância, como na primeira vez em que fui à casa de prostituição e acompanhei a distribuição de preservativos e lubrificantes. Além disso, observei as profissionais do sexo solicitando que o CRIS também as visitasse para realizar a testagem. Quando perguntamos sobre a percepção da liderança em relação à atuação do poder público no cuidado com essas mulheres, a entrevistada relatou:

> O que tende a acontecer, principalmente aqui no município de Sobral e com o fechamento da Astras, é que ela perca o acesso ao preservativo como ela precisa. Ela de precisa de preservativo, mas ela nem sempre vai pegar. O tanto que uma pessoa casada precisa por semana, ela precisa para 01 dia, né? Não posso dizer que ela é comum. Ela não pode chegar lá no posto de saúde, ou seja, lá onde for, CRIS ou PSF, e dizer assim “olha eu tô precisando de 300 preservativos”, não tem quem vá dar a ela, vão dar 3 tirinhas, 3 tirinhas ela usa em uma noite, um dia, né? 3 tirinhas ela vai usar, a mulher comum ela pode comprar um gel, e passar 06 meses sem, sem… né? Bastante tempo, a trabalhadora do sexo precisa do gel com muito mais frequência do que outra mulher, tendeu? Então, assim, a meu ver, a meu ver, tem que haver uma política que proteja essa mulher não quando ela esteja doente, mas antes do adoecer dela (Liderança Astras).

Sobre os dados trazidos até aqui, acerca da ausência do olhar e do cuidado, sobretudo do município, se os serviços não chegam até essas mulheres, e se elas não têm acesso ao direito de proteção e prevenção, a quem recorrer, uma vez que a associação que faz essa mediação está finalizando suas atividades? E acrescenta:

> As dificuldades maiores são o acesso delas aos programas de saúde, porque, como eu coloquei, eu vou pegar uma mulher comum e vou pegar uma trabalhadora do sexo, todas duas têm o mesmo direito de procurar o posto, só que uma procura e vai embora, e a outra tem necessidade quase que diária e não tem, e não tem quem esteja lá pra tá dando informação a ela, muitas vezes elas são discriminadas dentro dos postos, muitas vezes, não é só uma vez não, a questão de pegar o preservativo é uma, a questão de ter, é… como eu posso te dizer, de se identificar, de chegar e “olha eu sou trabalhadora do sexo”, nenhuma quer se identificar assim, eu preciso de 10 preservativos diário, ou 5 preservativo diário, elas não têm esse tanto de preservativo pra receber dentro dos postos de saúde de Sobral, não têm! (Liderança Astras).

Ainda sobre a importância da prevenção e informação:

> As dificuldades que são postas a elas principalmente em relação à prevenção, não só a AIDS como outras infecções, tanto visto, que tá aí um monte de menino nascendo com sífilis, por que que nasce com sífilis? Porque a mãe lá na sua gestação adquiriu ou bem antes da gestação, nunca cuidou, não é explicado, não é entendido por ela que tem que fazer pré-natal bem-feito com consultas mensais, isso quem faz são outras pessoas, o posto de saúde não vai pra dentro do cabaré (Liderança Astras).

As vivências das profissionais do sexo são permeadas por uma série de obstáculos que dificultam o acesso às políticas públicas. Silva, Sampaio e Méllo [-@silva2022cuida] apontam que, no campo da saúde, as políticas públicas muitas vezes resumem suas ações à sexualidade, limitando-se à distribuição de preservativos, laqueadura e planejamento familiar. Dessa forma, as profissionais do sexo são estigmatizadas não só pela sociedade, mas também pelo Estado, sofrendo diversas formas de violência institucional. De acordo com Tabuchi e Santos [-@tabuchi2021violencia], ao buscar políticas públicas voltadas para esse público, encontram-se apenas orientações sobre sexualidade, sem propostas para combater a violência contra as profissionais do sexo e sem indicadores sobre a violência que elas sofrem. Assim, compreende-se que existem dimensões culturais, simbólicas, territoriais e institucionais que contribuem para a invisibilidade dessas mulheres por parte do Estado e da sociedade civil.

Sobre sua percepção acerca da violência, preconceito sofrido e enfrentado pelas profissionais do sexo:

> A violência, hoje em dia elas já sabem que tem a lei Maria da Penha, elas já sabem, quando elas sofrem elas vão, mas elas vão como mulher e não como trabalhadora do sexo, e poucas vão, poucas vão. Uma das grandes violências que eu percebo é a violência quando a pessoa não quer pagar o programa, e eles discutem e vão as vias de fato, outra coisa é em relação à perspectiva do que aquilo seja uma violência, a visão dela... é perceber que aquilo é violência, muitas vezes ela não percebe, ela acha que é um fato comum, e é uma violência. A diferença da violência sofrida pela mulher casada e pra mulher trabalhadora é o seguinte: a mulher casada ela pode apanhar, mas ela vai atrás e só de um único homem; a trabalhadora não, ela pode levar ‘pea’ duas, três vezes. E uma das coisas que tá muito relacionado a essa violência hoje é o uso indevido de drogas, porque fazem o consumo de drogas, eu sempre digo: antigamente tinha as cafetinas, hoje tem os traficantes, então tem algumas têm uso de drogas e têm que pagar. E, quando não paga, morre; quando não paga, apanha, pra isso vai (Liderança Astras).

Prada [-@prada2018putafeminista] já anunciava que o feminismo chegou ao puteiro, e não foi graças às feministas conservadoras. Com a ausência da proteção institucional, essas mulheres criam suas próprias redes de cuidado e suporte. Sobre isso, de acordo com Silva [-@silva2014implicacoes], fica implícito que na zona existe muito mais que programa, a zona é o encontro das mais variadas expressões e articulações, assim como oportunidades de agregação e criação de diálogos. Essas mulheres carregam marcas de relações desiguais, mas elas se reinventam.

Podemos pensar também, como nos aponta Patriarca [-@patriarca2018donas], na ambivalência da figura da cafetina/cafetão, que, de alguma forma, protege essas mulheres, garantindo a segurança no ambiente de trabalho, ao mesmo tempo em que se coloca como figura de autoridade. Olhando tais relações, as fronteiras entre a cafetina má e a dona de casa de prostituição que cuida formam uma zona borrada e nebulosa. Dessa forma, essas mulheres vão criando códigos a partir desses lugares, assim como as relações de afeto, sororidade, chegando ao que Piedade [-@piedade2017dororidade] chama de “dororidade”, que significa a cumplicidade entre mulheres negras, pois é sabido que existem dores que só as mulheres negras reconhecem, por isso trazemos também esse conceito, tendo em vista que a sororidade não vai alcançar todas as experiências vividas por mulheres em seu existir histórico.

Redes de afetos são criadas entre as prostitutas, bem como com o cafetão/cafetina, as quais possibilitam a criação de um suporte, tendo em vista que, em sua maioria, as famílias não sabem sobre a profissão que exercem, vivendo assim uma vida dupla. Conforme Patriarca [-@patriarca2018donas], essas relações são de fundamental importância no cotidiano dessas mulheres, tendo em vista que algumas não sabem ler, não sabem calcular e acabam contando com a ajuda umas das outras para sobreviver, existindo, assim, de forma simultânea, relações de rivalidade e apoio.

## Considerações finais

Conforme observado ao longo deste estudo, não conseguimos o resultado esperado na versão que foi apresentada na qualificação, pois, diante do planejado, chegaríamos neste momento com três entrevistas realizadas: profissional do sexo em atividade, profissional do sexo aposentada e liderança da Astras. Além disso, destacamos o momento de autocuidado, que seria composto pelas estações de cuidado (nutricionista, dermatologista, educadores físicos, oficina de automaquiagem e redução de danos), para o qual já tinham sido feitas as parcerias para a realização desse momento.

Dentre as tantas angústias produzidas pela não realização do proposto, a maior delas foi a não realização desse momento de autocuidado, pois já estava planejado e articulado, faltando apenas a captação de recursos financeiros. Perceber e aceitar isso que não seria posto em prática, que não aconteceria, foi como a sensação de não ter conseguido entregar o principal objetivo deste programa de mestrado: devolver algo para a população que estudei. Além disso, perceber que esse público em específico, como já citado, precisa de permanência da pesquisadora, pois que são relações que se movem com muita fluidez, bem como entrar nesse campo, é saber que sempre nos depararemos com novas mulheres. Assim, é preciso presença diária, e não falo aqui de estar todos os dias, mas manter frequência, é necessário manutenção desses vínculos para que não se fragilizem. Essa foi uma das lições mais importantes que recebi e carrego para futuros estudos com essa população. Compreendo que o campo nos possibilitou experienciar e aprender.

As mulheres visíveis, tidas como invisíveis, precisaram construir formas de se proteger mesmo daqueles que ofertam possibilidades de cuidado. Isso se apresenta como uma urgência, um olhar humanizado do município/Estado na elaboração de estratégias de cuidado e de políticas públicas voltadas para esse público. Essa é a nossa forma de perceber que um olhar diferente promoverá uma mudança no sentido de um cuidado ampliado, pois, quando a violência contra essas mulheres entrar nas estatísticas, elas serão vistas. Compreendemos a grandeza desses momentos vivenciados a partir dessas experiências, as quais contaram não apenas com os instantes vividos com essas mulheres, mas também com toda a preparação que antecedeu as visitas à associação e à casa de prostituição, bem como com as reuniões de grupo para a preparação desses momentos, o compartilhamento das angústias provocadas pelo campo, assim como a sensação diante da impotência imposta pelos limites das fronteiras. Até onde poderíamos ir? Estar no campo é, sobretudo, estar atenta às convocações, as quais, por muitas vezes, foram simbólicas: “queria conversar com você”, “você é mãe?”, “você pode explicar o significado dessa palavra?”, “quando vocês vêm de novo?”.

Percebemos que, mesmo com um planejamento prévio, não foi possível cumprir como estava no papel, o que entendemos como uma forma de produção de sentidos do campo, que não foram os nossos sentidos, mas das mulheres. Elas foram dando um outro contorno a partir do momento que demonstraram não apenas desejo, mas disponibilidade de fala. Percebemos que elas não acessam os dispositivos de saúde, e que tal fato não se dá pela “escolha da invisibilidade”, mas sim por não se permitirem ser mais violentadas do que já são. Diante do peso do estigma e da ausência de políticas de proteção e cuidado para essas mulheres cada vez mais as redes de afeto e proteção na zona se fortalecem, um ato de resistência e reinvenção de novos outros modos de resistir para poder existir, a tal da invisibilidade escolhida pelo fato de não saírem publicando que são prostitutas, ou mesmo, ao acessar os dispositivos, não se nomearem como profissionais do sexo, é uma tentativa de se protegerem muitas vezes de olhares e de julgamentos.

Chega-me agora ao pensamento uma fala de Sojourner Truth que sempre me atravessa quando a leio ou escrevo sobre mulheres que se prostituem: “E eu não sou uma mulher?”, uma mulher igual a nós, que construímos essa pesquisa, mas não como nós, pois não falamos do mesmo lugar. Sinto que conviver com essas mulheres me fez sentir, “com elas”, preconceitos, sonhos, amor, anseio por dinheiro, família, violência e esperança de uma vida melhor. Temos muito a fazer nesse lugar, compreendo que aquilo que nos atravessa e nos mobiliza se torna nosso também, é da nossa conta, e, sendo assim, vejo como uma convocação do campo, não se tratando de fazer para, mas de fazer com, caminhos que a psicologia andarilha nos permite percorrer, esse fazer para além do setting, esse chegar junto a e, a partir da necessidade apresentada, propor estratégias que façam sentido para essas mulheres.
