---
author: 
  - name: Thamyles de Sousa e Silva
    url: https://lattes.cnpq.br/3266568917899957 
    orcid: 0000-0001-5235-9312
    email: thamylessousa@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Juliana Viera Sampaio
    url: http://lattes.cnpq.br/9556200287516417
    orcid: 0000-0001-5770-244X
    email: julianavsampaio@hotmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
lang: en
toc-title: "Table of contents"
language: 
  title-block-author-plural: "Authors"
filters:
  - section-bibliographies
bibliography: sousa_silva_saude_homens_trans_en.bib
reference-section-title: References
---

# Discussion circle on healthcare access for trans men in Ceará countryside

## Introduction

This study is an excerpt from the ongoing master's research of the author. The aim is to discuss healthcare practices for trans men in countryside Ceará, based on the experience report of a discussion circle. To begin the discussion, it is notable that there is a constant pursuit, from a very young age, to affirm the biological sex of a child. Through this, a process begins defining the toys, clothes, accessories, and colors the individual will use.

Thus, to affirm that an individual is constituted only through binarity is to adopt a logic that perpetuates the suffering of those who do not fit in. In this way, it becomes evident that language, as pointed out by Foucault [-@foucault1996], produces effects and materializes in our daily lives, institutions, transmitted discourses, and power relations. In this way, people produce their subjective processes. This can contribute to more violations, as individuals are almost obliged to perform certain stereotypes, which are not necessarily those that give meaning to their bodies.

According to Ávila [-@avila2014], discussing transsexuality requires reflections that go beyond biological conceptions, not reducing individuals to such a criterion. In the present study, the decision was made to specifically engage with trans men due to the considerable lack of visibility directed towards this group, which has already been addressed in some research, particularly regarding access to healthcare [@avila2014; @nery2011].

In this study, the term "trans men" is used based on Àvila's [-@avila2014] considerations, which define them as individuals who were born in biologically female bodies but did not identify as such. Thus, they came to identify as male bodies based on their own experiences and the construction of their identity throughout life. In this context, there are many discussions about transsexuality, but most studies focus on transfeminine issues without addressing transmasculine topics [@passos2018].

The importance of discussing this topic lies in fostering a more humanized perspective on the needs of trans men in healthcare services and actively contributing to intervention processes in the health field. This qualitative study, based on an experience report, aims to discuss healthcare access for trans men in rural Ceará through an experience report.

## Method

This is a qualitative study of the experience report type, which, according to Ludke and André [-@ludke2014], involves describing the process and focusing on the participants' perspective through direct contact with the researcher. Therefore, this study refers to a workshop held with four trans men about healthcare access for this group. They were contacted using the "Snowball" technique. This technique is used to access hard-to-reach groups or to study delicate private issues, where one person mediates and refers others with the required profile for the research [@bockorni2021].

Moreover, "workshops are spaces with the critical potential for negotiating meanings, allowing for the visibility of arguments, positions, but also shifts, construction, and contrast of versions" [@spink2014, p. 33]. Additionally, a field diary was used as a research instrument to capture expressions and as a way for the researcher to include insights beyond what was heard at that moment [@kroeff2020]. The workshop took place on March 16, 2024.

An initial contact was made with a trans man in a medium-sized town in rural Ceará, an active participant in the social movements present in the municipality, and from his referrals, contact with others interested in participating was made possible. Four people attended, while others who were invited could not participate.

The workshop lasted five hours, which is essential to highlight as it became apparent that the group needed to talk and share their experiences. One of the participants pointed out that there is a lack of connection among trans men in the municipality, with difficulties in gathering and being together as a collective. Therefore, these meetings are rare; when they occur, they become spaces of significant exchange.

Thus, the workshop was divided into three stages: 1. Introduction dynamics; 2. Cards with questions related to healthcare, covering topics such as challenges in accessing healthcare, services with which they have a connection, hormone therapy, mental health, and perceptions about access; 3. Writing on a sheet of paper words that summarize how they want healthcare to be for trans men.

## Results and Discussion

### Unfolding the Collective Meeting: A Path to Be Taken

The master's research from which this workshop is derived specifically focuses on trans men due to the invisibilities experienced by this group within policies and dialogues about transsexuality [@ferreira2022], making it essential to consider the care of these individuals within specific spaces, such as healthcare. Initially, the focus was on discussing healthcare access for trans men, how they have accessed the healthcare system, and the impacts, violence, and support they experienced during their quest for care. Some reflections were made through an initial contact via the workshop and are presented here.

In the first activity, participants were asked to write down five significant moments of their lives, as a way to bring them closer, revealing personal aspects of each one, considering that they knew each other. Still, there was no closer relationship among some of them. When discussing the moments they wrote down, all four pointed out that starting their transition was extremely significant in their lives. The events they wrote about revolved around college, work, family, transition, and the recognition of their bodies.

One of them, who is 30 years old, stated that he began his transition in 2013 and commented that at that time, it was challenging to access information, especially healthcare services, further stating:

> Participant 1: In 2013/2015, when I sought out professionals to assist me at the beginning of hormone therapy, I couldn't get any kind of care at the health center (psychologist, endocrinologist...), because they want us to adapt to the system, not the other way around. What I notice the most is that professionals don't understand the definition of gender and sex; when I say I'm a trans man, they ask, "So you want to become a girl?" They don't understand that I'm a man; the trans part comes afterward (Field diary, 03/16/2024).

Regarding hormone use, many criticisms arose. Another participant stated that "hormones for trans men are much harder to get and more expensive" and that something even more harmful is the fact that they cannot access an endocrinologist through the Unified Health System (SUS), only through private consultations, which are not easily accessible due to financial constraints. One of them said that he began hormone therapy privately because he had health insurance, but if he hadn't, he wouldn't have been able to do so.

Also, through jokes, they mentioned that sometimes there is no other way but self-medication, without medical supervision. This reinforces the importance and urgency of endocrinologists in this process, mainly due to health risks. The second activity involved written questions on cards, allowing the dialogue to continue. Regarding challenges in accessing healthcare, they pointed out:

> Participant 1: I'm afraid to seek care and be rejected.\
> Participant 2: I would like to find a service with professionals who are specialized in meeting the needs of trans people, professionals who actually see me (Field diary, 03/16/2024).

The dialogue about healthcare access led to a discussion about the distress of needing to see a gynecologist. They said they prefer female professionals, considering their experiences with male professionals have been disastrous and disrespectful. They pointed out that there is a lack of understanding among professionals about transsexuality, which makes it difficult for them to be treated. Moreover, they mentioned several times that they procrastinate until the last minute to make medical appointments and only do so when it's urgent, often having not gone for a long time. Still, when possible, they opt for private services rather than SUS, justifying it by saying there is an option to choose the healthcare professional.

Participant 1 shared an experience illustrating that professionals with sensitivity to offer humanized care within SUS are rare. He recounted a situation that occurred at the health center, which was one of the few times he felt the professional showed sensitivity:

> Participant 1: When I went to the health center for the first time to see a gynecologist, the receptionist called my name and looked at me with many questions, not understanding why I wanted a consultation, asking if I was in the right place, and I had to explain that I am a trans man. After that, she went to tell the doctor. When the gynecologist called me, she said, "Come on, let's answer questions about your girlfriend," which I thought was super cool on her part to avoid embarrassment. She advised me to bring my mom to the gynecologist because her name would be on the consultation, avoiding me feeling uncomfortable (Field diary, 03/16/2024).

This situation was discussed with the others, who affirmed the rarity of such an attitude, pointing out that most professionals do not try to act with such sensitivity, making it difficult for trans men to seek services due to the embarrassment they face, leading them to give up. Thus, they pointed out some of their perceptions about access, such as:

> Participant 1: There is a lack of professionals who understand the needs of trans people and understand that trans people are not all the same.\
> Participant 2: They don't just kill us with physical violence; I wish it were only that. They take away opportunities, freedom, safety, and even my name (Field diary, 03/16/2024).

Next, we discussed mental health and the connection with services. We observed no ongoing connection with healthcare services; use is sporadic and generally occurs only in emergencies or through private care. Regarding mental health, they stated that there is excessive suffering among them concerning the disrespect they face throughout life, which reverberates into numerous harms. At that moment, they also spoke about services and how they are treated:

> Participant 4: I feel like I go to these services and have to teach more than I learn (referring to CAPS).\
> Participant 3: I want professionals to know how to treat a trans man, to understand that I have needs beyond being trans. There's also the fact that I always want to fit in, not recognizing myself in the mirror. It brings a lot of suffering.\
> Participant 1: They always associate us with genitalia, looking at me with fetishistic eyes, which creates a lot of difficulty in relationships, and it affects us (Field diary, 03/16/2024).

Participant 4 stated that he uses the municipality's Psychosocial Care Center (CAPS, an acronym for Centro de Atenção Psicossocial, which are community-based mental health centers). He does not like the service because professionals do not respect his social name. He goes only because he needs medication but doesn't like it. Through all the statements made, some themes emerged and were frequently mentioned throughout the meeting, referring to gender performativity[^sousa_silva_saude_homens_trans_en-1]. Some examples were:

[^sousa_silva_saude_homens_trans_en-1]: Butler [-@butler2003] emphasizes that performativity affirms the constitution of gender as acts, representations, and gestures, thus considering it as a process of becoming and constructing oneself through such.

> Participant 1: What I heard a lot from my family was, "You can't be trans; God gave you a uterus to have children." In other words, they don't understand that I can be a trans man and still get pregnant. We know very well that it's not just about pregnancy (Field diary, 03/16/2024).\
> Participant 2: People usually don't get my pronoun wrong, but as soon as I paint my nails, they start getting it wrong (Field diary, 03/16/2024).\
> Participant 3: To protect myself and avoid having to explain, when I request an Uber, for example, I immediately get in "scratching my crotch" so they don't ask anything (Field diary, 03/16/2024).

Through the statements made, it was possible to see that there is a social demand for them to perform certain stereotypes to be seen as men. Thus, by failing to conform to established norms, gender identities outside the binary are rendered as failures [@butler2003]. It becomes apparent that if there is no full identification and adjustment to established social norms, then the body is not considered understandable by others. Consequently, the place to be assigned is marginalization, exclusion, and invisibility. Moreover, considering other ways of experiencing masculinity becomes almost unfeasible, such as by bringing the concept of transmasculinities[^sousa_silva_saude_homens_trans_en-2].

[^sousa_silva_saude_homens_trans_en-2]: Simone Ávila [-@avila2014] states that they are masculine identities constructed by trans men, with no universal model, being unique.

Butler [-@butler1990], in "Gender Trouble," recalls Julia Kristeva's concept of abjection to reflect on some concepts and developments regarding gender. Thus, intertwining this concept with the discussion, this place of invisibility directed at trans bodies "is what we do not want to see... they are abject bodies that we excrete" [@kristeva1982]. It is evident, through the discourses, that there is a demand for trans people to conform to an aesthetic expectation of the gender they identify with. Such a fact creates an almost indispensable and fundamental requirement to perform certain gender stereotypes. However, wouldn't the demand to conform to cisnormativity be a form of violence in itself?

Participant 3 also stated that his family often questions him about having long painted nails, doubting "how can you want to be a man with long painted nails?" The ambiguity seems to generate incomprehension regarding the body that presents itself, thus, the closer one is to the established norm of what is considered femininity and masculinity, the more that body is seen as legitimate [@leite2008].

There is a requirement that there should be no confusion when looking at such a body, that they already have their name rectified in their documents, and that clothing and body expressions should avoid any confusion between masculinity and femininity. All participants stated that they see this cisnormative pressure on all men, but for trans men, it is even more demanding and becomes exhausting to have to reaffirm who they are constantly. Bento [-@bento2006] discusses how the understanding of gender and sexuality in transsexuality is linked to sexual difference. Thus, as the body moves away from the established binary norms, it does not become comprehensible to those who see it. Additionally, it is located in social delegitimization, as no discourse establishes it as true due to its incomprehensibility. According to Leite Júnior [-@leite2008]:

> As gender norms help shape what we understand as "human, "the closer a person's performativity is to the ideal of a "true" femininity or masculinity, the more that person will be understood as human... The more gender norms of a given period are internalized and, mainly, expressed as an "inner nature" through clothing, behavior, feelings, and desires, the more the notion of a "true" woman or "true" man is reinforced (p. 215).

Thus, the body acquires meaning through language, leaving behind denial, exclusion, and abjection [@butler1990]. The concept of abjection explored by Butler refers to something that exists but is not recognized by the symbolic order; it is understood as something that lies within the realm of negation [@paiva2022]. Thus, it exists but is denied. The existing division of sex and gender operates in a normative space, establishing criteria for such bodies to be considered human.

> Participant 2: I will leave it written on paper that when I die, I want to be buried in a suit. They don't respect me alive, l*et al*one dead (Field diary, 03/16/2024).

The statement above reveals a demand for the recognition of one's body, imposing itself and making it almost obligatory for the individual to leave a written request for respect, showing that they occupy a marginalized existence. Consequently, delegitimization operates in many spaces [@paiva2022], highlighting that this impossibility of existence also concerns places where these bodies are erased.

Thus, from the workshop held, it becomes clear that the exclusion and delegitimization of their bodies becomes a barrier that prevents them from accessing healthcare services, as they perceive a lack of openness to difference, leading them to distance themselves and not exercise their rights. This results in a lack of connection and continuous care, "would there then be a policy that includes this multiplicity of differences?" [@martins2018, p. 65]. In the third and final stage of the workshop, when they were asked to write on a sheet of paper words summarizing how they want healthcare to be for trans men, the words were: updated, continuous, accessible, welcoming, respectful, inclusive, free, and participatory.

## Final Considerations

Thus, given the discussions raised, an attempt is made to reflect on the consequences that may arise concerning the constant need to affirm the trans body through others, which is also correlated with their modes of subjectivation. The ways are diverse, such as seeking to mark a place that resembles the binary norm, for example, when one of the participants states that he "scratches his crotch when getting into an Uber," thus performing a difference in what is considered masculine, thereby affirming his identity to the one who sees him. Thus, it is noted that performing certain stereotypes can sometimes provide the individual with a place of affirmation within specific groups.

From the experiences shared through the workshop with the four trans men and the discussion held thus far, the pressing question that arises is: Does the more tremendous suffering come from not identifying with one's body or from the place of abjection imposed by others? Bringing forth this place of abjection means discussing the various forms of exclusion that trans bodies are often assigned. Why think of the subject's existence solely based on recognition strictly linked to other knowledge and not the knowledge of the body itself, which speaks?
