---
author: 
  - name: Roberta de Fátima Rocha Sousa
    url: http://lattes.cnpq.br/3212189083748734
    orcid: 0009-0003-1182-6916 
    email: robertafrsousa@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Juliana Vieira Sampaio
    url: http://lattes.cnpq.br/9556200287516417
    orcid: 0000-0001-5770-244X 
    email: julianavsampaio@hotmail.com 
    affiliations: 
      - name: Universidade Federal do Ceará
lang: en
toc-title: "Table of contents"
language: 
  title-block-author-plural: "Authors"
filters:
  - section-bibliographies
bibliography: sousa_violencia.bib
reference-section-title: Referências
---

# "My way, i made my revolution": The multiple layers of violence against women engaged in prostitution

## Introduction

> "My way, I made my revolution and moved forward" [@leite2009filha, p. 31]

Reflecting on the invisibility, or even the deliberate invisibilization, of a stigmatized profession, particularly that of women engaged in prostitution, is essential to constructing new forms of care and attention in public policies for this population group. Despite the repeated discourse that prostitution is the oldest profession in the world, the focus is more on the act of prostitution rather than on the women who perform it. Thus, according to Grant [-@grant2021dando], women engaged in prostitution are perceived as invisible, voiceless, and hidden, even in their public nudity.

Examining this phenomenon through the lens of psychology allows us to understand the implications regarding these women's ways of life and the significance of their subjectivities, problematizing symbolic and physical aggression, silencing processes, stigmatization, socialization modes, and coping mechanisms [@silva2014implicacoes]. In this context, we advocate for the possibility of producing a more sensitive perspective on these issues and fostering transformations in the academic field through the researcher's involvement. Studies and research on this topic within psychology are relatively recent, which makes this research even more impactful.

We frame our journey through the concept of Wandering Psychology, where we walk in the rhythm of events, considering the circumstances of the field. The aim was to conduct the research alongside the women, respecting their singularities and subjectivities. According to Quadros [-@quadros2023experiencias], Wandering Psychology is one that also accompanies people in their mobilities, that walks alongside, moves, and leaves the place, giving new meanings. According to the Michaelis online dictionary [-@michaelis2024andarilho], a wanderer is "someone who walks a lot; someone who walks or travels extensively." This metaphor broadens a way of thinking about psychology, as in our praxis, we are wanderers, walking through different lands, at various times, with the risk of errancy and, at the same time, the surprises of pleasant discoveries.

Thinking through Wandering Psychology, walking through different lands, exploring spaces, and building possible paths, as Quadros [-@quadros2023experiencias] points out, we understand that there is still much to be done in this regard, realizing that what crosses and moves us also becomes ours. We understand walking as a call from the field, not about doing for, but doing with—these are paths that Wandering Psychology allows us to explore. Considering the dimension of researching the violence experienced by these women means knowing that they will not be waiting for us, nor will they have much time available to be with us, requiring the researcher to make greater adjustments in this territory, respecting the dynamics presented by the field. We believe this research can contribute to fostering greater engagement of psychology in addressing this topic and creating new practices based on welcoming, promoting health, and providing comprehensive care to these women. According to Maia *et al*. [-@maia2002profissionais], the daily lives of women engaged in prostitution involve aspects such as violence and physical aggression from clients, conflict with the police, concealment of the profession from family and friends, and moral conflict regarding the practice of commercial sex.

The interest in studying the violence experienced by these women arose from these concerns that have existed since our undergraduate studies, emphasizing the importance of revealing and exposing what is invisible, making it visible; in some way, it is about challenging the structure that is imposed as a norm, even if symbolically. The body of a woman engaged in prostitution is considered public property. According to Butler [-@butler2015quadros], some lives are seen as less worthy, and protection and violence are differentially distributed to them, thereby demarcating which lives matter and which do not.

The relevance of this research is justified by the need to expand the academic scope on the reality of sex workers, particularly regarding the interior region of Ceará. A search of the CAPES Platform and Virtual Health Library (BVS) databases found only three articles on prostitution in Sobral/CE, covering 2007, 2008, and 2013. Thus, we hope this research may serve as a starting point for other studies and the development of new care practices for these women.

In this text, we present an excerpt from the master's research results, institutional visits conducted, and an interview with the leader of the sex workers' movement in the city. Based on these experiences, we established the main objective of this study: to analyze the different experiences of violence faced by sex workers.

## Partnerships That Sustain Fieldwork

The execution of this research was only possible through partnerships that enabled access to the field and the union of the master's program with university extension activities. These partnerships provided greater support in the activities and increased the possibilities for interventions with the women. Thus, this section presents the partnerships that made these encounters possible.

### SUSEX

The Center for Studies and Extension on Subjectivation and Sexuality (SUSEX) is a project linked to the psychology course at the Federal University of Ceará, Sobral *campus*. Its main objective is to promote gender equity and respect for sexual diversity, seeking to foster resistance through creative power, countering the homogenization and standardization of ways of living.

In this sense, SUSEX seeks to carry out teaching, research, and extension activities that engage undergraduate and graduate students, as well as members of the community outside the university, developing actions primarily aimed at promoting sexual and reproductive health rights, as well as other activities related to gender and sexuality discussions.

### Astras[^sousa_violencia_en-1]

[^sousa_violencia_en-1]: Information on this topic comes from the podcast available at: https://open.spotify.com/episode/7bxxM2TzxqutZghrAp9NBF?si=8ea52faf26de475

The Sobral Association of Sex Workers (ASTRAS) took its first steps in 1999 and was officially registered in 2000. It is an NGO to advocate for the rights and protections of women engaged in prostitution, through partnerships and resources, to prevent STIs and HIV in the city of Sobral/CE. It is worth noting that at that time, no entities or health services were working specifically with the sex worker population, providing services or psychoeducation on topics related to healthy, infection-free sexual lives.

Thus, after identifying the need for places to meet these women's demands and create safe spaces, ASTRAS was founded. Initially, the goal was to understand the specific needs of these women, conduct active outreach regarding their lifestyle, and facilitate access to the municipality's health services, which were often limited due to the prejudice faced.

With the support of the Family Health School, active outreach was conducted, as mentioned earlier, to register both the brothels and their owners, as well as the workers employed there. Initially, care services were provided in the brothels; later, as the service gained more familiarity, which was then conducted by the Coas—the Counseling and Serological Guidance Center—referrals were made. Later, partnerships were established with neighborhood health posts for better guidance on referrals and services. In cases of abortion, the teams would sometimes transport the women to the Santa Casa de Misericórdia de Sobral.

During the implementation of ASTRAS, resistance to accessing brothels and beginning to recognize these women beyond the stigma was evident, understanding them in their entirety as mothers, women, daughters, and partners, and not just through the activities they performed. The woman who led the creation of ASTRAS is no longer in charge of the association[^sousa_violencia_en-2].

[^sousa_violencia_en-2]: During a visit to ASTRAS, we were informed that the place where the association operated had to be vacated because, due to the lack of financial support from the Sobral/CE Municipal Health Department, it became impossible to cover rent, water, and electricity expenses. Currently, the association has been taken in by the Casa Madre Anna Rosa Gattorno, serving as a support point for activities with sex workers.

To maintain her anonymity, we refer to the woman present during the association's creation as Girassol. At that time, Girassol was a manicurist and seamstress living close to the brothels. In addition to doing the prostitutes' nails, she also sewed for them. Girassol became a figure of care; during her manicure and sewing services, she would listen to the accounts of suffering and difficulty related to prostitution work. Girassol became a support network for them, as a relationship of trust existed.

## Methodological Approach

This is a qualitative study, and this methodology was chosen because we believe it contributes to understanding the social and subjective aspects of various practices in our society. We used intervention-implication research as the theoretical-methodological framework, which, according to Romagnoli [-@romagnoli2014conceito], "occurs when there is a rupture in the plane of forces that connect in the encounters 'between' the researcher and their object of study" (p. 49). This practice enhances the research process and involves the researcher being open to the field.

According to Aguiar and Rocha [-@aguiar2007micropolitica], in this perspective, the concept of implication is linked to the ability to make connections, to make shifts that lead us to consider new inventions. This perspective of conducting research is essential, as we were present in the daily lives of sex workers, not only listening to their narratives but also participating/intervening in an implicated way to promote better living conditions.

In this conception, conducting intervention research in psychology, according to Cavalcante [-@cavalcante2016sobre], means accepting the invitation to shift and self-critique within the field of psychology itself. By adopting participatory alternatives that distance us from the fallacious ideals of neutrality, we understand this type of research as a tool through which action is not about but with subaltern groups, producing an effect even while it is being conducted, involving researching with rather than for.

Regarding qualitative research, Godoy [-@godoy1995introducao] states that, through it, a phenomenon can be better understood in the context in which it occurs, and the analysis can be conducted from an integrated perspective. Thus, qualitative research allows for a closer relationship between the researcher and the subject being studied within their context, understanding this subject as a whole, and enabling interventions based on experiences in the field. It is understood that there is no neutrality in conducting research, as the researcher is affected by emotions and also affects others. Regarding the researcher's involvement:

> The qualitative researcher systematically reflects on who they are in the investigation and is sensitive to their personal biography and how it shapes the study. This introspection and recognition of biases, values, and interests (or reflexivity) typifies current qualitative research. The personal self becomes inseparable from the researcher self. This also represents honesty and openness to research, recognizing that all investigation is value-laden [@creswell2007projeto, p. 187].

When we consider the relationships of affection and trust—which are constructed and established from these positions so that we can understand that we are talking about women who carry stigmas and are labeled—we see the importance of not imposing norms or working with concepts of right and wrong. Our goal is to respect the uniqueness and subjectivity of each individual, creating spaces for the construction of affect where they can express themselves freely and without judgment.

In our research, we also used the methodological strategy of participant observation, as this approach goes beyond simple observation, involving a diverse set of methodological techniques that demand the deep involvement of the researcher with the studied situation. Furthermore, Ludke [-@ludke1986pesquisa] suggests that observation reports should incorporate a reflective dimension beyond mere description. In this sense, the researcher is encouraged to include personal observations, speculations, feelings, problems, impressions, doubts, uncertainties, surprises, and disappointments in their narrative.

### Location

Sobral is a municipality in the interior of Ceará, with a population of 210,711 inhabitants, according to the 2020 estimate by the Brazilian Institute of Geography and Statistics (IBGE). According to the Human Development Index (HDI), it is the 5th most populous municipality and the second most developed in Ceará. The research took place in the city of Sobral/CE in the following locations: a brothel in the central market and the Casa Madre Anna Rosa Gattorno in the Sinhá Sabóia neighborhood.

### Data Collection

Here, we present an excerpt from the master's research. Three institutional visits were conducted — ASTRAS, CMC, and CRIS— to understand the operation and flow of sex workers, as well as verify statistics of violence against them. Finally, we conducted a semi-structured interview with the leadership of ASTRAS, intending to gain a better understanding of the importance of the association for sex workers, as well as understanding the impact of the absence of public policies directed at these women.

Ludke [-@ludke1986pesquisa] emphasizes that recording these experiences through writing is an important way to enable people in society to access and understand different issues, especially in today's world, where information technology plays a significant role. Kroeff *et al*. [-@kroeff2020diario] argue that conducting fieldwork is an essential strategy in research, as it integrates theoretical propositions with practical experience in constructing contextualized knowledge. In many qualitative exploratory studies, especially in psychology, it is common practice to use field diaries as a methodological tool. These diaries are used to record and subsequently analyze the experience of both the researcher and the participants. Field diaries were tools used to document and communicate these experiences in the research context, making them more accessible and understandable to a broader audience.

Thus, we chose to write field diaries as a valuable strategy for producing and analyzing the interaction between the researcher and the research field. This occurs through problematizing memory, habit, and creating focused attention to modulate the experience of both the researcher and the surrounding world. We emphasize that field diaries were used in all stages of the research.

In addition to the field diary, as a data collection instrument for this research, one socioeconomic questionnaire and one semi-structured interview, which was recorded and later transcribed, were conducted with the leadership of ASTRAS. According to Manzine [-@manzine2004entrevista] (só tem de 2004) (2012), the interview's main characteristic is a script with open questions, being suitable for studying a phenomenon with a specific population. It is important to highlight the significance of this interview, as the leadership conveyed to us throughout this study the difficulties present in the field of public policies and the mediation with the field itself.

It is worth noting that the original project intended to interview five women, but we were only able to interview the leadership of ASTRAS, as the field was not conducive to conducting the other interviews. Several contact attempts were made between February and June 2024 via WhatsApp messages and phone calls to schedule interviews, resulting in five confirmations. However, when they did not attend, the ASTRAS leadership would contact us to inform us. In an attempt to carry out the interviews, we contacted the brothel owner, who told us she would speak with her husband to see what he thought, which was the last contact. None of the interlocutors responded to messages or answered calls, which caused some frustration as we could not conduct the intended data collection.

Understanding and respecting the closure of the field in the absence of possibilities to continue, we faced reflections on how much this field requires continuity, as while we were present, it was possible to sense the various emerging possibilities. Furthermore, we needed to step back to await the ethics committee's approval. Regarding this, it became evident how detrimental the withdrawal was, as returning felt like starting over. Thus, given the circumstances, we worked with what the field allowed us to access, conducting only one interview with the leadership to document and use in this research. It should be noted that the interviewee signed the Informed Consent Form (ICF).

### Data Analysis

We used the theoretical-methodological approach of discursive practices and meaning production for data analysis. When relating discursive practices to meaning production, we assume that meanings are not found in language as materiality but in discourse that transforms language into a tool for constructing reality. In the case of reporting, the act of reporting is, in fact, explanatory in its relationship with the context. As Spink and Pinheiro (não seria lima?) (2013) point out, the report focuses on what the subject narrates, the arguments used, and the explanation given to validate the narrative.

For data analysis, we used idea association maps, which, according to Spink and Lima [-@spink2013rigor], aim to systematize the process of analyzing discursive practices by seeking the formal aspects of both linguistic construction and the repertoires used in this construction. Furthermore, they are considered instruments with a dual purpose: to support the interpretation process and facilitate the communication of the steps underlying the interpretative process.

### Ethical Aspects

This research was submitted to the ethics committee for research involving human beings, following the Guidelines and Regulatory Standards for Research involving human subjects, according to Resolution 466/12 of the National Health Council. This was done in such a way that the voluntariness of the participant was respected. She neither received nor paid to participate in this research. Confidentiality and anonymity were also guaranteed. The research objectives were explained, ensuring the interviewee could withdraw participation at any time without any prejudice [@brasil2012resolucao]. Participation in this research was formalized by signing the Informed Consent Form (ICF), with a favorable opinion no. 6.662.189, dated February 21, 2024.

## Institutional Visits

### Astras and Brothel

Two visits were made to Casa Madre Anna Rosa Gattorno, which will be described later. These visits aimed to understand the functioning and flow of ASTRAS.

During the second visit to ASTRAS, which took place in April 2023, the researcher was invited to visit one of the brothels located near the central market of Sobral/Ce. It is important to mention that this was the first contact with the place, and the possibility of this visit occurring on that day had not been considered. Driven by the desire to enter the field, the invitation was accepted. On that occasion, the leadership provided some instructions, such as how to act in case of an approach by a man and, if it happened, to remember that we were in their environment, so we should respond firmly but not aggressively. Thus, we referred to the field diary to report the experiences of that occasion:

> We arrived... the entrance looked like a regular bar, with a few tables, about three women drinking at one of the tables at the entrance, and a man with a surly expression at the door. At first, I thought he was a customer, but then I imagined he might be a kind of security guard since he remained in the same spot the whole time (Field Diary 04/24/23).

We were introduced to a woman in charge of the place, who invited us to visit her establishment and the brothel next door. About the first house:

> I saw how big it was, with several tables, chairs, and a corridor with many doors. I looked quickly because there were some women there, and I didn't want them to think I was observing them. There was also a large box in that space, which I believe was one of those jukeboxes where people put in coins and choose songs (Field Diary, 04/24/23).

The second house was separated from the first by a business with a very narrow entrance, and many men were drinking. My first impression was that it was just a bar.

> I walked in, greeting people with a half-smile, not knowing how to behave but trying my best not to make eye contact. It was a large space, crowded, I think all the tables were occupied, a corridor full of doors, and at the end, a kitchen separated by a gate (Field Diary, 04/24/23).

> "When we were leaving, we were approached by one of the women asking about exam collection" (Field Diary, 04/24/23).

We felt it was important to mention this statement, as it reflects an awareness of the importance of health care and the pursuit of public policies. During the visits to ASTRAS and through conversations with the leadership, as well as during this visit to the brothel, we realized that sex workers did not access health services, which caught our attention at the time. Social stigmas and moral judgments by health professionals can often prevent these women from using services. Corroborating Maciel *et al*. [-@maciel2020percepcoes], it is vital that professionals from any public policy, not just health, are trained to welcome and provide the proper referrals and guidance humanely and supportive to sex workers. Given that this was the first contact with the field, it was a moment of great intensity and impact, where something theoretical turned into a lived experience.

### Casa da Mulher Cearense (CMC) and Infectious Disease Reference Center (CRIS)

To learn about public policies aimed at protecting women from violence and preventing sexually transmitted infections (STIs) and HIV/AIDS, we visited CMC and CRIS.

In April 2023, we visited Casa da Mulher Cearense. Upon arriving at the facility, while waiting to speak with the person in charge, we spoke with the receptionist, who briefly explained the facility's purpose. Then, the researcher was received and explained the purpose of the visit. The interlocutor expressed some joy upon hearing about the "invisible group"[^sousa_violencia_en-3] and went on to say that the facility had no demand from sex workers but would consult the psychosocial sector to be sure.

[^sousa_violencia_en-3]: Expression used by the person in charge of CMC.

> I felt embarrassed by her tone of authority and judgment, and I didn't even ask the questions I had planned. I made assumptions instead. I asked if a sex worker came to the house in cases of violence. She replied that they were referred to the DDM, and even if they received this service, they wouldn't register it unless the woman insisted on being heard, and only then would they open a record (Field Diary 04/25/23).

A statement that further reinforces invisibility, a refusal to acknowledge. Prada [-@prada2018putafeminista] states that "never a woman like the others, the prostitute is beyond the border, where so-called decent women cannot be. And it is she, and only she, whom society chooses to condemn and stone" (p. 35). As heard and felt, it was like a judgment, a final sentence, a statement implying an unworthiness of protection unless she "insisted."

We increasingly understand that a facility designed for women does not consider all possibilities of womanhood. Some women receive care, necessary services, and possible referrals, but if we talk about sex workers, the approach is different. It is already known that the Maria da Penha Law does not cover the violence suffered by sex workers, but as seen during this visit, an expansion of care is needed. It is a facility for women, so we understand that all women should be able to access it, but as observed, not only do sex workers not access it, but the facility is also not open to them. Finally, we talked about our desire to make sex workers visible at the municipal level, and once again, we were surprised by the response:

> They prefer to be invisible, perhaps as a way to protect themselves. At that point, I understood that sex workers had no place in that house (Field Diary 04/25/23).

In March 2023, we visited CRIS, already feeling some apprehension because the staff member who answered was very rude when we called to schedule the visit. When he heard the term prostitute, he interrupted and said that the term should not be used because it was derogatory and that I should study to avoid saying such nonsense. I tried to explain that the term was not incorrect, but he raised his voice, and I fell silent.

> I felt deeply distressed after that call because I felt attacked and silenced, even after identifying myself as a researcher. I kept wondering how these women could access that place if they said they were prostitutes and heard they were not (Field Diary 04/05/23).

Gabriela Leite [-@leite2009filha] argues that changing the term prostitute to sex worker or sex professional is akin to an apology. For this movement, it is essential to embrace the term and not shy away from it.

We were received by the person in charge, to whom we explained the reason for our visit: to verify whether sex workers accessed the service and if it was possible to obtain statistics of such access. We were informed that even if they self-identified, the only way to know would be to check each medical record individually. When a quick search was done in the system using terms such as sex worker, prostitute, sex professional, or work-related violence, no data was found. Notably, the system itself does not include sex worker as an occupation, and it is essential to note that the notification form only recognizes domestic/intrafamilial violence. Cases of extrafamilial/community violence only include children, adolescents, women, the elderly, persons with disabilities, individuals with mental disorders, indigenous peoples, and the LGBTQ community. As a result, when analyzing the notification form, we realize that it does not directly include sex workers, leaving it to the person filling it out to ask this question more directly. However, it takes a lot of sensitivity to approach even this kind of care, and as seen, these women rarely seek out such a facility.

> Several times, she said that my research was very difficult, that it would be very difficult to find data, even after I explained that my research did not depend on those data. Then she asked if I had already defended my thesis. I said no, and she asked why I didn't change my research, as it would be very difficult. I could hardly believe what I heard, and I simply replied that because it was difficult, I was determined to continue researching (Field Diary 05/02/23).

From this, we understood that even if sex workers accessed that facility, there were no statistics of such access. We also noticed the unease of the person we talked to, as she could not answer our questions. Once again, she emphasized the difficulty of analyzing all the medical records, which number over 35,000, to determine a figure. She mentioned that actions with sex workers only occur when they are requested, and since CRIS serves 55 municipalities, they cannot address this population adequately.

We identified the absence of statistics in Sobral regarding the violence experienced by sex workers and the healthcare services available to them, even though the city has these facilities. This means we have an alarming situation where no records of sex workers' access to these public policies are available. As Ribeiro [-@ribeiro2019quem] asserts, improvements for an invisible reality will never be considered if a reality is not named.

What is evidenced by these visits is indeed curious, given that we are dealing with facilities where the first one is sought by women victims of violence and the second works on preventing STIs and HIV. This leads us to question why the municipality fails to acknowledge these women. It is well known that we have the Maria da Penha Law, but we also know that it does not cover sex workers.

> Nowadays, they already know about the Maria da Penha Law, they know it, and when they suffer, they go, but they go as women and not as sex workers, and few do (Leadership Interview, 03/27/24).

Thus, we perceive that violence against women, especially those who engage in sex work, has been (and is) normalized, considering the stigmas associated with this work, placing them in various vulnerable situations: gender violence, racial violence, family violence, discrimination, financial instability, poverty, and health risks. We can view these aspects through the lens of intersectionality, as a crossroads that creates a network of many layers of inequality. As Akotirene [-@akotirene2022interseccionalidade] states, "intersectional thinking leads us to recognize the possibility of being oppressed and of collaborating with violence" (p. 45).

Even with the creation of public policies for women, these do not assist all women equally. The 2022 Violence Atlas, published by IPEA (Institute for Applied Economic Research), presents statistics on violence against women, such as the femicide of Black women, urban/outside home violence, and violence (physical, psychological, torture) against the LGBTQIAPN+ community. Still, no statistics are available on violence against women who engage in sex work.

These factors indicate that violence against prostitutes is invisible, as there are no statistical records on it, nor specific public policies. Such policies are only mentioned in STI control policies. Silva and Ximenes [-@silva2017not] state that violence against prostitutes remains hidden within the realm of gender-based violence. It is necessary to understand the nuances that violence can have beyond what can be found in common sense, as there seems to be a normalization of this phenomenon. Being a woman in our society is already a situation of vulnerability, due to unequal power relations in which women are seen as submissive and inferior to men.

## Interview with Astras Leadership

The interview with the ASTRAS leadership took place on March 27, 2024. It lasted 27 minutes, was recorded, and subsequently transcribed. We talked about the importance of the association, as, as seen so far, women do not access public policy facilities. Thus, the association acts as a mediator, making referrals for exams, distributing condoms, and promoting actions aimed at sex workers. However, the association is in the process of ceasing its activities, as the health department canceled the funding that was intended for its maintenance.

> The worst blow Astras suffered was from the current government, which took away a meager contribution of a thousand reais, which at least allowed us to have a headquarters. Without a headquarters, there are no projects, and we can't move forward. I can't create a project for the health department, I can't create a project for Germany or any other institution that works with this population because we don't have a headquarters. Why don't we have a headquarters? Because we don't have money to pay the rent. It's not fair for a person working voluntarily to still have to take money out of their own pocket to pay so that Sobral can say, oh, we have a policy—we have no policy, none (Astras Leadership).

The importance of ASTRAS for these women is evident by accessing this field. Even if sex workers do not seek out the association, it reaches out to them. On several occasions, I perceived this importance, such as the first time I went to the brothel and witnessed the distribution of condoms and lubricants. In addition, I observed sex workers asking CRIS to also visit them for testing. When we asked about the leadership's perception of the public authorities' role in caring for these women, the interviewee said:

> What tends to happen, especially here in Sobral, and with the closure of Astras, is that they lose access to the condoms they need. They need condoms, but they don't always go to get them. The amount a married person needs per week, they need for one day, right? I can't say they're common. They can't just go to the health center or wherever—CRIS or PSF—and say, "look, I need 300 condoms," nobody is going to give them that; they'll give three strips, and three strips are used in one night, one day, right? They'll use three strips. A regular woman can buy a bottle of lubricant and go six months without it, without... right? Quite a while, but a sex worker needs lube much more frequently than another woman, got it? So, in my view, there needs to be a policy that protects these women, not only when they're ill but before they get sick (Astras Leadership).

Regarding the data presented so far, about the lack of attention and care, especially from the municipality, if services do not reach these women, and they have no access to the right to protection and prevention, who can they turn to, considering that the association that provides this mediation is shutting down? She adds:

> The biggest difficulties are their access to health programs because, as I said, if I take a regular woman and a sex worker, both have the same right to go to the health center. The regular woman goes and leaves, but the other has almost daily needs and no one there to give her information. Often, they are discriminated against at health centers, not just once. The issue of getting condoms is one, and also the matter of identifying themselves, of coming in and saying, "look, I'm a sex worker." None of them want to identify themselves that way. "I need 10 condoms a day or five condoms a day," and they don't have that many condoms available at health centers in Sobral, they don't! (Astras Leadership).

On the importance of prevention and information:

> The difficulties they face, especially regarding prevention, not just AIDS but other infections, considering how many babies are being born with syphilis, why are they born with syphilis? Because their mothers acquired it during pregnancy or even before, and never received care. It's not explained, it's not understood by them that they need to have proper prenatal care with monthly check-ups. This is done by others; the health center doesn't go into the brothel (Astras Leadership).

The experiences of sex workers are permeated by a series of obstacles that hinder their access to public policies. Silva, Sampaio, and Méllo [@silva2022cuida] point out that in the field of healthcare, public policies often reduce their actions to sexuality, limited to distributing condoms, sterilization, and family planning. Thus, sex workers are stigmatized not only by society but also by the state, suffering various forms of institutional violence. According to Tabuchi and Santos [-@tabuchi2021violencia], when seeking public policies for this population, one finds only guidelines about sexuality, with no proposals to address violence against sex workers and no indicators about the violence they experience. It becomes clear that there are cultural, symbolic, territorial, and institutional dimensions that contribute to these women's invisibility by the state and civil society.

Regarding her perception of violence, prejudice experienced, and faced by sex workers:

> Violence—nowadays, they already know about the Maria da Penha Law, they know it, and when they suffer, they go, but they go as women and not as sex workers, and few go, very few go. One of the major forms of violence I see is when someone refuses to pay for a session, and they argue and get into a fight. Another is in relation to perceiving it as violence—her perspective... it's understanding that it is violence. Often, she doesn't perceive it; she thinks it's a common occurrence, but it is violence. The difference between the violence suffered by a married woman and a sex worker is that a married woman might be beaten, but she only deals with one man, whereas a sex worker can be beaten by two or three men at a time. One of the factors that is closely related to this violence today is the misuse of drugs because drugs are consumed. I always say: in the past, there were madams; today, there are drug dealers, and some use drugs and have to pay. And when they don't pay, they get killed; when they don't pay, they get beaten. That's how it goes (Astras Leadership).

Prada [-@prada2018putafeminista] already pointed out that feminism had arrived at the brothel, but it wasn't thanks to conservative feminists. Without institutional protection, these women create their networks of care and support. In this regard, according to Silva [-@silva2014implicacoes], it is implicit that in the zone, there is much more than just sex work; the zone is a place for encounters of the most diverse expressions and articulations, as well as opportunities for aggregation and dialogue creation. These women carry the marks of unequal relationships, but they reinvent themselves.

We can also think, as Patriarca [-@patriarca2018donas] points out, about the ambivalence of the figure of the madam/pimp, who, in some way, protects these women, guaranteeing safety in the work environment while also asserting themselves as an authority figure. Looking at these relationships, the boundaries between the bad madam and the brothel owner who cares form a blurred and nebulous zone. In this way, these women create codes based on these spaces, as well as relationships of affection and sorority, leading to what Piedade [-@piedade2017dororidade] calls "painority," which means solidarity among Black women, as it is known that there are pains that only Black women recognize. Therefore, we also bring this concept, considering that sorority will not encompass all the experiences lived by women in their historical existence.

Networks of affection are created among prostitutes, as well as with the pimp/madam, which makes it possible to create a support system, given that, in most cases, their families do not know about the profession they practice, thus leading a double life. According to Patriarca [-@patriarca2018donas], these relationships are of fundamental importance in these women's daily lives, considering that some of them are illiterate, do not know how to do calculations and rely on each other to survive, thus coexisting with both rivalry and support simultaneously.

## Final Considerations

As observed throughout this study, we did not achieve the expected results presented in the qualification version. According to the initial plan, we should have conducted three interviews by now: an active sex worker, a retired sex worker, and Astras leadership. In addition, we highlight the moment of self-care, which would have involved care stations (nutritionist, dermatologist, physical educators, self-makeup workshop, and harm reduction), for which partnerships had already been established to make this moment happen.

Among the many frustrations arising from not achieving what was proposed, the greatest was not being able to carry out this moment of self-care, as it had already been planned and articulated, with only the financial resources left to be obtained. Realizing and accepting that it would not take place, that it would not happen, was like the feeling of failing to deliver the main objective of this master's program: to give back something to the population I studied. Furthermore, realizing that this specific population, as mentioned before, needs the researcher's continuous presence, these relationships move with great fluidity, and entering this field means knowing that we will always encounter new women. Thus, a daily presence is needed—not every day, but maintaining frequency is essential to keep these bonds from weakening. This was one of the most important lessons I learned and carry forward for future studies with this population. I understand that the field allowed us to experience and learn.

The visible women, perceived as invisible, had to build ways to protect themselves even from those who offer them care possibilities. This presents itself as an urgency, a humanized look from the municipality/state in developing care strategies and public policies for this population. This is our way of understanding that a different approach will bring about change toward expanded care because, when violence against these women enters the statistics, they will be seen. We understand the significance of these moments experienced from these experiences, which included not only the moments spent with these women but also all the preparation that preceded the visits to the association and brothel, as well as group meetings to prepare for these moments, the sharing of anxieties provoked by the field, and the sense of helplessness imposed by the boundaries. How far could we go? Being in the field is, above all, being attentive to the calls, which were often symbolic: "I wanted to talk to you," "Are you a mother?", "Can you explain the meaning of this word?", "When are you coming back?"

We realized that even with prior planning, it was not possible to fulfill everything as written on paper, which we understand as a way of producing meaning from the field, which was not our meaning but theirs. They shaped the situation differently as they demonstrated not only the desire but also the availability to speak. We realized that they do not access health facilities, not because of the "choice of invisibility" but because they do not allow themselves to be further violated than they already are. Given the weight of stigma and the lack of protective policies for these women, networks of affection and support in the zone are becoming increasingly strong, an act of resistance and reinvention of new ways to resist to exist. This so-called chosen invisibility, resulting from not publicly declaring that they are prostitutes or even identifying as sex workers when accessing facilities, is often a way to protect themselves from the judgmental gaze.

I am now reminded of a quote by Sojourner Truth that always comes to mind when I read or write about women in prostitution: "Ain't I a Woman?" A woman just like us who built this research, but not like us, we do not speak from the same place, but I feel that living alongside these women made me feel "with them," experiencing prejudice, dreams, love, money, family, violence, and hope for a better life. We have much to do in this area, and I understand that what touches us and mobilizes us becomes our responsibility, is our business. Therefore, I see this as a call from the field, not about doing for them but doing with them, pathways that wandering psychology allows us to tread—doing beyond the setting, getting involved, and proposing strategies that make sense for these women based on their needs.
